### ISSUE TITLE
css.properties.-webkit-line-clamp - Latest ios not working

### ISSUE THREAD

**Issue by KarthikAdyar** [mdn/browser-compat-data#15518] opened 2022-03-25 14:44 UTC
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.-webkit-line-clamp`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp
* Report started: 2022-03-25T14:05:26.342Z

</details>

**Comment by lukewarlow** [comment] 2022-03-27 13:13
Are you able to provide more (realistically any) information about the issue you're having.

The demo on the provided link works fine on an iOS 15.4 simulator, and a real iPad OS 15.4 device.

![image](https://user-images.githubusercontent.com/32498324/160282999-e7fbc526-3f6f-4017-a70b-8bf5bebc7849.png)

Given this the data would seem to still be correct and I would suggest filing a webkit bug if you have in fact found a regression on latest iOS.

**Comment by KarthikAdyar** [comment] 2022-03-29 07:37
Try adding two p tags inside a main div and the line clamp in the div
<div class=""line-clamp-here"><p>Long text1</p><p>Long text2</p></div>
Check the results 

<img width="1277" alt="Screenshot 2022-03-29 at 1 05 26 PM" src="https://user-images.githubusercontent.com/44839038/160558636-fd5bf33e-5256-4247-ad3a-1f383bce717d.png">

<img width="1130" alt="Screenshot 2022-03-29 at 1 05 58 PM" src="https://user-images.githubusercontent.com/44839038/160558753-077744f1-5f90-4cbd-af83-e961e131ec6c.png">

**Comment by lukewarlow** [comment] 2022-03-29 07:40
Can you post a jsfiddle or equivalent link? Either way, first step would be to report to WebKit bug tracker.

**Comment by KarthikAdyar** [comment] 2022-03-29 09:39
<html>
<body>
  <div class="line-clamp">
    <p>
      Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
    </p>
    <p>
      Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
    
    </p>
  </div>
</body>

</html>

.line-clamp {
   display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 2;
  overflow: hidden;
}

**Comment by KarthikAdyar** [comment] 2022-03-29 09:41
`<html>
<body>
  <div class="line-clamp">
    <p>
      Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
    </p>
    <p>
      Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
    
    </p>
  </div>
</body>

</html>`

.line-clamp {
   display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 2;
  overflow: hidden;
}

**Comment by KarthikAdyar** [comment] 2022-03-29 09:43
``<html>
<body>
  <div class="line-clamp">
    <p>
      Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
    </p>
    <p>
      Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
    
    </p>
  </div>
</body>

</html>``

**Comment by KarthikAdyar** [comment] 2022-03-29 09:45
`<html>`

**Comment by KarthikAdyar** [comment] 2022-03-29 09:45
`<div class="line-clamp">
    <p>
      Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
    </p>
    <p>
      Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
    
    </p>
  </div>`

**Comment by lukewarlow** [comment] 2022-03-29 09:59
I asked for jsfiddle so I could quickly click on a link on iOS and test it. Either way I suggest directing this at the WebKit bug tracker not here.

**Comment by lukewarlow** [comment] 2022-03-29 13:46
https://jsfiddle.net/4Lqy78xw/ - here's a jsfiddle for it. Fwiw the behaviour I get in Safari I also get in Firefox, so it's potentially actually a Chrome "bug".

Firefox:

![image](https://user-images.githubusercontent.com/32498324/160625478-faa51954-cf80-4131-9e7e-230f91d7148b.png)

Safari:

![image](https://user-images.githubusercontent.com/32498324/160625522-495df61d-073b-488c-b6ad-c9a83ed52561.png)

Chrome:

![image](https://user-images.githubusercontent.com/32498324/160625583-189a9912-3ee3-4ada-8c84-ad4c9e3dec12.png)

Also it's not just latest Safari nor iOS.

Either way I suggest going to the respective browsers bug trackers or somewhere like https://webcompat.com/issues/new as this isn't a BCD issue.

**Comment by KarthikAdyar** [comment] 2022-03-30 10:15
Know any better way to clamp 2 lines for such case

**Comment by queengooborg** [comment] 2023-08-06 20:03
I'm going to close this issue since it mostly seems to be a help request, and we are not a help forum.

**Closed by queengooborg** 2023-08-06 20:03 UTC
Labels: data:css :art:
