### ISSUE TITLE
api.Notification.Notification - chrome android has no support

### ISSUE THREAD

**Issue by ptman** [mdn/browser-compat-data#13737] opened 2021-11-25 13:14 UTC
#### What information was incorrect, unhelpful, or incomplete?

Chrome mobile since version 42 (?) doesn't support the Notification constructor. https://bugs.chromium.org/p/chromium/issues/detail?id=481856

#### What did you expect to see?

No support for chrome mobile in recent versions.

#### Did you test this? If so, how?

Yes, I get the error mentioned on the chrome bug.

<details>
<summary>MDN page report details</summary>

* Query: `api.Notification.Notification`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Notification/Notification
* Report started: 2021-11-25T13:12:53.420Z

</details>

**Comment by queengooborg** [comment] 2021-12-25 03:32
Duplicate of #7923.

**Closed by queengooborg** 2021-12-25 03:32 UTC
Labels: data:api :rabbit2:
