### ISSUE TITLE
css.types.color.lab - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by Bonzey2416** [mdn/browser-compat-data#18902] opened 2023-02-13 13:53 UTC
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Chrome 110 introduces lab() and lch() colors. However, they can only work by enabling #enable-experimental-web-platform-features flag in chrome://flags.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

The Chrome should be 110 and a flask above the number.

### Did you test this? If so, how?

No

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://caniuse.com/css-lch-lab

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/lab

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.types.color.lab`
* Report started: 2023-02-13T13:49:26.084Z

</details>

**Comment by queengooborg** [comment] 2023-02-13 16:21
Duplicate of your other issue, #18902.

**Closed by queengooborg** 2023-02-13 16:21 UTC
Labels: needs triage 🔎
