### ISSUE TITLE
`offset-anchor` doesn't seem to be supported in Chrome

### ISSUE THREAD

**Issue by wbamberg** [mdn/browser-compat-data#10936] opened 2021-06-10 15:41 UTC
The table for https://developer.mozilla.org/en-US/docs/Web/CSS/offset-anchor says this property is supported in Chrome since v79. But looking at the [live sample](https://developer.mozilla.org/en-US/docs/Web/CSS/offset-anchor#examples), the property doesn't seem to have an effect in Chrome.

Firefox:

<img width="860" alt="Screen Shot 2021-06-09 at 9 11 57 PM" src="https://user-images.githubusercontent.com/432915/121555089-8f9c6b80-c9c7-11eb-9360-02c61e86419e.png">

Chrome:

<img width="903" alt="Screen Shot 2021-06-09 at 9 12 07 PM" src="https://user-images.githubusercontent.com/432915/121555108-95924c80-c9c7-11eb-89cd-459a287ba51e.png">

Am I missing something or is this property actually not supported?

**Comment by Blakelist7** [comment] 2021-06-15 19:21
I am also facing same issue. Even tried adding `-webkit-` to `data-property` but hard luck.

**Comment by queengooborg** [comment] 2021-12-24 23:19
Duplicate of #10495.

**Closed by queengooborg** 2021-12-24 23:19 UTC
Labels: data:css :art:
