### ISSUE TITLE
Internet Explorer is dead

### ISSUE THREAD

**Issue by nitrologic** [mdn/browser-compat-data#16773] opened 2022-06-23 19:06 UTC
Removing Internet Explorer from Browser Compatibility Charts will allow charts to reflect better the state of browser compatibility in 2022. 

Exhibit A - https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

**Comment by queengooborg** [comment] 2022-06-23 19:58
Duplicate of #15333.

**Closed by queengooborg** 2022-06-23 19:58 UTC
