### ISSUE TITLE
javascript.statements.for_await_of - Is not supported on Safari 11

### ISSUE THREAD

**Issue by zaygraveyard** [mdn/browser-compat-data#14823] opened 2022-02-04 12:43 UTC
#### What information was incorrect, unhelpful, or incomplete?
`for await .. of` is marked as supported on Safari 11

#### What did you expect to see?
Support started from Safari 12

#### Did you test this? If so, how?

See https://github.com/evanw/esbuild/issues/1930

<details>
<summary>MDN page report details</summary>

* Query: `javascript.statements.for_await_of`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of
* Report started: 2022-02-04T10:54:28.376Z

</details>

**Comment by Elchi3** [comment] 2023-02-22 16:55
Duplicate of https://github.com/mdn/browser-compat-data/issues/14522

**Closed by Elchi3** 2023-02-22 16:55 UTC
Labels: data:js :pager:
