### ISSUE TITLE
International support for hyphens:auto better than reported

### ISSUE THREAD

**Issue by Rolf-B** [mdn/browser-compat-data#21402] opened 2023-11-30 13:18 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens

### What specific section or headline is this issue about?

Browser Compatibility

### What information was incorrect, unhelpful, or incomplete?

The table says that Chromia support hyphenation only for lang="en". That's not true any more, I am using Microsoft Edge and Google Chrome with de-DE and hyphens:auto works. Even with slight differences between -1996 and -1901 orthography

And that's another error in the table: de-AT-1901 is an invalid locale, the script-subtag belongs between language and region: de-1901-AT

### What did you expect to see?

A green checkmark for chromia in the de rows, although I can't tell you the first supporting version and I can't tell if the dictionaries are complete or error free.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/hyphens`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/hyphens/index.md
* Last commit: https://github.com/mdn/content/commit/5e7d1f9ae2cce0cb3f7693dfb8dc6e8d375b2231
* Document last modified: 2023-07-18T00:16:24.000Z

</details>

**Comment by queengooborg** [comment] 2023-12-05 21:36
Duplicate of #15470.

**Closed by queengooborg** 2023-12-05 21:36 UTC
Labels: data:css :art:
