### ISSUE TITLE
css.selectors.picture-in-picture - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by tregoning** [mdn/browser-compat-data#17973] opened 2022-10-11 07:14 UTC
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Support data seems to indicate that Chrome supports :picture-in-picture but that's not the case ATM.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### Did you test this? If so, how?

Their own demo page (https://googlechrome.github.io/samples/picture-in-picture/css-pseudo-class) for this feature no longer works (but it does in Safari)

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://bugs.chromium.org/p/chromium/issues/detail?id=940404

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:picture-in-picture

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.picture-in-picture`
* Report started: 2022-10-11T07:04:21.446Z

</details>

**Comment by queengooborg** [comment] 2022-10-11 08:54
Duplicate of #17972.

**Closed by queengooborg** 2022-10-11 08:54 UTC
Labels: data:css :art:, needs triage 🔎
