### ISSUE TITLE
http.methods - missing PATCH compatibility

### ISSUE THREAD

**Issue by KPGDL** [mdn/browser-compat-data#14879] opened 2022-02-08 09:03 UTC
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `http.methods`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods
* Report started: 2022-02-08T09:02:06.632Z

</details>

**Comment by queengooborg** [comment] 2022-02-08 09:08
This issue was closed because it appears to be empty. The issue is not different from the issue template and no actionable information has been provided.

If this has been closed in error, edit the title and body, and post a follow-up comment.

**Closed** 2022-02-08 09:09 UTC
Labels: invalid :no_entry_sign:
