### ISSUE TITLE
html.elements.input.type_datetime-local - Time picker not showing in firefox browser

### ISSUE THREAD

**Issue by inilaypatel** [mdn/browser-compat-data#20564] opened 2023-08-18 09:52 UTC
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

datetime-local is not working on firefox properly. It is not showing timepicker. My firefox version is 116.0.2 (64-bit)

### What did you expect to see?

Display timepicker.

### Did you test this? If so, how?

Checked it on mdn web docs website.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.input.type_datetime-local`
* Report started: 2023-08-18T09:46:35.522Z

</details>

**Comment by queengooborg** [comment] 2023-08-19 09:51
Looks like this is a duplicate of #16138.

**Closed by queengooborg** 2023-08-19 09:51 UTC
Labels: needs triage 🔎
