### ISSUE TITLE
api.fetch - No Node.js compatibility info for fetch()

### ISSUE THREAD

**Issue by ma1ted** [mdn/browser-compat-data#14611] opened 2022-01-20 09:30 UTC
#### What information was incorrect, unhelpful, or incomplete?
The Browser compatibility table for the fetch api would be more helpful if it included compatibility info for Node.js.
This would help new users by informing them fetch is not supported in Node.
It would also bring the page in line with other pages that do include Node in their Browser compatibility tables.

#### What did you expect to see?
A column next to Deno titled `Node.js`, with a red box in every row - signifying `No support`

To maintain consistency, Node compatibility information should also be added to all fetch method and property pages.

#### Did you test this? If so, how?
Testing not required.

<details>
<summary>MDN page report details</summary>

* Query: `api.fetch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API
* Report started: 2022-01-20T09:21:01.014Z

</details>

**Comment by Araxeus** [comment] 2022-03-29 20:08
it seems fetch is available as an experimental flag in https://nodejs.org/en/blog/release/v17.5.0/

**Comment by Rexogamer** [comment] 2022-04-21 11:23
It's now enabled by default (albeit still considered experimental) [in Node 18](https://nodejs.org/en/blog/release/v18.0.0)

**Comment by thw0rted** [comment] 2022-08-04 15:39
Is this a duplicate of https://github.com/mdn/browser-compat-data/issues/15676 ?

**Closed** 2022-08-05 11:55 UTC
Labels: data:api :rabbit2:
