### ISSUE TITLE
The `npm run render` command throws an error if there are non-JSON files present

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/browser-compat-data#402] opened 2017-09-22 12:55 UTC
...for example, I am using a Mac, and the system creates those helpful but annoying `.DS_Store` files in all directories. when I try to run `npm run render`, the command tries to read the `.DS_Store` file first and then throws an error.

Could we make it so that the command ignores non-JSON files?

**Comment by Elchi3** [comment] 2017-09-22 14:04
I can't reproduce (on Ubuntu anyway). Can you provide the error message / stacktrace?

**Comment by chrisdavidmills** [comment] 2017-09-22 14:05
Hrm, maybe it is just with dot files?

Anyhow, the error looks like so:

```cmills-42208:browser-compat-data chrismills$ npm run render 'css.properties.background'

mdn-browser-compat-data@0.0.6 render /Users/chrismills/git/browser-compat-data
node test/render "css.properties.background"

/Users/chrismills/git/browser-compat-data/css/.DS_Store:1
(function (exports, require, module, __filename, __dirname) { 


SyntaxError: Invalid or unexpected token
   at createScript (vm.js:56:10)
   at Object.runInThisContext (vm.js:97:10)
   at Module._compile (module.js:542:28)
   at Object.Module._extensions..js (module.js:579:10)
   at Module.load (module.js:487:32)
   at tryModuleLoad (module.js:446:12)
   at Function.Module._load (module.js:438:3)
   at Module.require (module.js:497:17)
   at require (internal/module.js:20:19)
   at processFilename (/Users/chrismills/git/browser-compat-data/index.js:13:64)

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "render" "css.properties.background"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! mdn-browser-compat-data@0.0.6 render: `node test/render "css.properties.background"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdn-browser-compat-data@0.0.6 render script 'node test/render "css.properties.background"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdn-browser-compat-data package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node test/render "css.properties.background"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdn-browser-compat-data
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdn-browser-compat-data
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chrismills/git/browser-compat-data/npm-debug.log```

**Comment by ddbeck** [comment] 2017-09-22 18:50
I was able to reproduce this on my Mac by opening a compat data directory (e.g., `css`) in Finder, rearranging the icons, then running the render command. I think you can get a similar effect on non-Mac systems by creating a non-empty file that's not a valid JSON object (e.g., run `echo ',' >> css/.foo`).

**Comment by Elchi3** [comment] 2017-09-29 09:11
This should be fixed by https://github.com/mdn/browser-compat-data/pull/411

**Closed by Elchi3** 2017-09-29 09:11 UTC
Labels: bug

**Comment by chrisdavidmills** [comment] 2017-09-29 09:47
Cool, thanks!
