### ISSUE TITLE
Pointer Lock API - Chromium based android browsers don't seem to support pointer lock api.

### ISSUE THREAD

**Issue by Vixeliz** [mdn/browser-compat-data#14640] opened 2022-01-23 00:02 UTC
Android 12, samsung internet and chrome latest stable versions 

On the support chart chrome android and samsung internet are listed as full support.
I expected the browsers I tested (chrome and samsung internet) to capture the mouse however the mouse was not captured.
I tested via checking out the mdn pointer lock api example, some itchio games that use pointerlock, etc.
https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API

**Comment by queengooborg** [comment] 2023-12-05 05:51
Duplicate of #19829.  (Well, technically, this issue came first, but the other issue has more details.)

**Closed by queengooborg** 2023-12-05 05:51 UTC
Labels: data:api :rabbit2:
