### ISSUE TITLE
CSS folder structure - add functions folder

### ISSUE THREAD

**Issue by ramiy** [mdn/browser-compat-data#10563] opened 2021-05-21 12:51 UTC
Ok, so the [CSS folder](https://github.com/mdn/browser-compat-data/tree/main/css) had 4 sub-folders:

* **at-rules**
* **properties**
* **selectors**
* **types** - includes both data-types and functions

CSS has over 100 functions and only ~25 data-types. In October 2020 we added **CSS functions** page (see https://github.com/mdn/sprints/issues/3838 and https://github.com/mdn/sprints/issues/3848).

We didn't do the separation in browser compatibility repository. Currently all the browser compatibility json files for CSS functions are inside the **types** folder. We need to create a new **functions** folder, move the functions-related JSON files to the new folder.

Also, we need to update the function related content pages, to change the **browser-compat** tag. For example, in [calc()](https://developer.mozilla.org/en-US/docs/Web/CSS/calc()) page we need to replace `browser-compat: css.types.calc` with `browser-compat: css.functions.calc`

@chrisdavidmills @rachelandrew

**Comment by ddbeck** [comment] 2021-05-26 17:13
Thanks for opening this issue, @ramiy.

This is something we considered relatively early in the migration from wiki tables to BCD. See https://github.com/mdn/browser-compat-data/pull/642. At the time, we decided that CSS functions are a specific value notation, not a separate category from other value types, so we chose not to separate them from other values. Apart from this issue, I don't recall this having come up since #642.

Changing this would be somewhat disruptive, requiring a semver major release, so I'm a little reluctant to change this. But I'm not a CSS expert, so perhaps this categorization merits revisiting. I'd be especially interested in @rachelandrew's take on this.

(Also, cc: @Elchi3, since this is a possible breaking change.)

**Comment by ramiy** [comment] 2021-05-26 17:57
Thanks for the reference, but #642 was opened 3.5 years ago and I'm not sure it's relevant anymore.

Take `calc()` for example:

First of all, according to #642 it should be a **sub-feature of the property it belong too**. But `calc()` can be used in many and inside other functional notations.

Secondly, [in BCD repo](https://github.com/mdn/browser-compat-data/blob/main/css/types/calc.json) `calc()` is not a sub-feature, seems like it has it's own sub-features.

Not sure #642 is relevant anymore in 2021.

But your are right about the technical side. I do want to hear if it is possible to implement without breaking stuff.

**Comment by rachelandrew** [comment] 2021-05-26 18:26
I'm not sure what benefit it brings to move them, other than it might feel a bit tidier. While I'm generally a fan of putting things in neat folders, in this case, it seems like it creates a bunch of work for no real benefit. Is there a issue I'm not understanding that is caused by the current structure?

**Comment by ramiy** [comment] 2021-05-26 19:43
@rachelandrew beyond the obvious benefits, it also resolves the issue of naming collision.

There should be a separate `url()` function and a separate `<url>` data-type. Another example is the `<image>` data-type and the `image()` function. One more is the `<color>` data-type and the `color()` function.

**Comment by rachelandrew** [comment] 2021-05-26 20:08
I guess I'm asking what these "obvious benefits" are.

And, we currently are able to represent `<image>` and `image()` etc. 

What I'm driving at is, are there enough benefits to make it worth the technical and editing work to do this? It seems like you want to do it because it's tidier, and I'd agree with that, but that might not be a compelling enough reason.

**Comment by ramiy** [comment] 2021-05-27 07:33
If the problem is the technical side and the editing work, we can break it into two steps:

* Move the JSON files to a new folder (none-breaking change).
* Replace `css.types.calc` with `css.functions.calc` (possible breaking change - need to check with @Elchi3).

**Comment by ddbeck** [comment] 2021-06-04 12:11
@ramiy In addition to the discussion above, I raised this in conversation with @Elchi3. Overall, it looks like there's just not enough interest—from BCD's consumers, subject matter experts, and maintainers—to justify making a breaking change (or diverging from our usual practices, when it comes to folder structure alone). As a consequence, I'll have to close this issue (and the related PR).

I realize this isn't the outcome you wanted. Nevertheless, thank you for opening this issue, and providing an illustration of the proposed changes in https://github.com/mdn/browser-compat-data/pull/10578.

**Closed by ddbeck** 2021-06-04 12:11 UTC
Labels: wontfix :-1:, data:css :art:
