### ISSUE TITLE
api.GPU - Incorrect support data related Chrome on Android

### ISSUE THREAD

**Issue by pjmlp** [mdn/browser-compat-data#22628] opened 2024-03-14 14:51 UTC
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

WebGPU support on Android via Chrome Mobile browser.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

WebGPU is now enabled by default in Chrome 121 on devices running Android 12 and greater powered by Qualcomm and ARM GPUs.

### Did you test this? If so, how?

https://developer.chrome.com/blog/new-in-webgpu-121

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebGPU_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.GPU`
* Report started: 2024-03-14T14:48:29.249Z

</details>

**Comment by pjmlp** [comment] 2024-04-03 08:25
Updated the title as suggested by the bot, Chrome Android information is still outdated.

**Comment by queengooborg** [comment] 2024-06-21 13:42
Closing this as a duplicate of #22159.

**Closed by queengooborg** 2024-06-21 13:42 UTC
Labels: data:api :rabbit2:
