### ISSUE TITLE
css.properties.scroll-behavior - <smooth in chrome and edge is not working!>

### ISSUE THREAD

**Issue by byrevx** [mdn/browser-compat-data#13839] opened 2021-12-03 00:51 UTC
#### What information was incorrect, unhelpful, or incomplete?
scroll-behavior: smooth; in chrome and edge is not working!

#### What did you expect to see?
Smoth scroll

#### Did you test this? If so, how?
Test in page https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior
Scroll to: A B C not working smoth !

Tested in:
Chrome Version 96.0.4664.45 (Official Build) (64-bit) , 
Microsoft Edge Version 96.0.1054.34 (Official build) (64-bit) 
and Not Working!

But Working in Firefox 94.0.2 (64-bit)

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.scroll-behavior`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior
* Report started: 2021-12-03T00:42:54.351Z

</details>

**Comment by AnilSeervi** [comment] 2021-12-07 13:36
It's working fine for me in those browsers.

I think you've tested it for `scroll-behavior: auto;` property, which is selected by default for the demo-example.
Switch to `scroll-behavior: smooth;` property in the left-side and test the demo for smooth scroll.

**Comment by byrevx** [comment] 2021-12-07 16:55
Hi, 

Thanks for the reply!

Tested with scroll-behavior: smooth; ... 

I disabled all addons, but it still doesn't work.Updated last version: Version 96.0.4664.93 (Official Build) (64-bit) , still doesn't work.
I have disabled the "Use hardware acceleration when available" option , still doesn't work.
 I tested it on my mobile phone and it's ok there, only Chrome Desktop doesn't work!

But, i find the problem ... chrome://flags/#smooth-scrolling option is disabled "default" !!!
Basically chrome decided "unilaterally" not to offer CSS support "by default" FOR #smooth-scrolling, but only for experienced and developers ...

I don't see the point, either it removes it permanently and thus it becomes clear that it is chrome, it is NOT 100% compatible with CSS Overflow 3, or it activates (enable) it at any normal installation!

Sistem:
Laptop Lenovo Legion, Ryzen 7 4800H, 16G RAM, Video Radeon &  GTX 1650 Ti
OS: Microsoft Windows 10 Pro (non-activated) [Version 10.0.19042.1348]

Emilian Robert Vicol
 

    On Tuesday, December 7, 2021, 03:36:57 PM GMT+2, Anil Seervi ***@***.***> wrote:  
 
 


It's working fine for me in those browsers.

I think you've tested it for scroll-behavior: auto; property, which is selected by default for the demo-example.
Switch to scroll-behavior: smooth; property in the left-side and test the demo for smooth scroll.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lukewarlow** [comment] 2021-12-16 12:38
Works fine for me on multiple different Chrome versions. If indeed there is a bug you've experienced I suggest making a bug in Chromiums bug tracker. As there's not an issue with the data could you close this issue please.

**Comment by queengooborg** [comment] 2021-12-25 03:40
I'm closing this issue because I'm unable to reproduce the issue either.  I think this is either a client configuration issue (flags could be the culprit; I'd reset them all to default), or maybe there's some weird bug that's only affecting your particular system...I have no idea.  😛

**Closed by queengooborg** 2021-12-25 03:40 UTC
Labels: data:css :art:
