### ISSUE TITLE
WeakRef - Opera 80 supports WeakRef but is shown as unsupported

### ISSUE THREAD

**Issue by pfriesch** [mdn/browser-compat-data#13174] opened 2021-10-29 11:21 UTC
#### What information was incorrect, unhelpful, or incomplete?
The combability page for Weak Ref shows that Opera 80 does not support WeakRef, when in fact it does.

#### What did you expect to see?
Opera 80 shown as green for WeakRef

#### Did you test this? If so, how?
I ran the example code from the [MDN page for WeakRef](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef) in Opera 80.

**Comment by queengooborg** [comment] 2021-12-25 03:09
Duplicate of #12523.

**Closed by queengooborg** 2021-12-25 03:09 UTC
Labels: data:js :pager:
