### ISSUE TITLE
api.createImageBitmap

### ISSUE THREAD

**Issue by liaoshl** [mdn/browser-compat-data#13593] opened 2021-11-18 08:19 UTC
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `api.createImageBitmap`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap
* Report started: 2021-11-18T08:03:23.816Z

</details>

**Comment by queengooborg** [comment] 2021-11-18 19:21
This issue was closed because it appears to be empty. The issue is not different from the issue template and no actionable information has been provided.

If this has been closed in error, edit the title and body, and post a follow-up comment.

**Closed** 2021-11-18 19:20 UTC
