### ISSUE TITLE
Issue with "AudioContext": (not working ios 15)

### ISSUE THREAD

**Issue by Jcarloscosta** [mdn/browser-compat-data#14414] opened 2022-01-03 17:34 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext

#### What information was incorrect, unhelpful, or incomplete?
Not working after updating to ios 15

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/audiocontext`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/audiocontext/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by Jcarloscosta** [comment] 2022-01-04 00:03
> > Not working after updating to ios 15
> 
> What exactly is not working?

/* Web Audio API audio variables */
var audioCtx = new (window.AudioContext || window.webkitAudioContext);
var audioBeep;
var audioSuccess;
var audioWarning;
var audioError;

/* Loads a sound file into a buffer. */
function loadSound(context, variableName, url) {
    
    /* Create request */
    var request = new XMLHttpRequest();
    request.open('GET', url, true);
    request.responseType = 'arraybuffer';

    /* Request load handler to decode audio */
    request.onload = function() {
        audioCtx.decodeAudioData(
            request.response,
            function(buffer) {
                context[variableName] = buffer;
            }
        );
    }

    /* Get audio file */
    request.send();
    
}

/* Load application sounds */
loadSound(this, 'audioBeep', '/app/sound_bip-checked.wav');
loadSound(this, 'audioSuccess', '/app/sound_success.wav');
loadSound(this, 'audioWarning', '/app/sound_warning.wav');
loadSound(this, 'audioError', '/app/sound_error.wav');

async function PlayBeep() {
        var aud = audioCtx.createBufferSource();
        aud.buffer = audioBeep;
        aud.connect(audioCtx.destination);
        aud.start(0);
}

/* Plays an operation completed with success sound. */
async function PlaySuccess() {
        var aud = audioCtx.createBufferSource();
        aud.buffer = audioSuccess;
        aud.connect(audioCtx.destination);
        aud.start(0);
}

/* Plays an operation completed with warnings sound. */
async function PlayWarning() {
        var aud = audioCtx.createBufferSource();
        aud.buffer = audioWarning;
        aud.connect(audioCtx.destination);
        aud.start(0);
}

/* Plays an operation completed with errors sound. */
async function PlayError() {
        var aud = audioCtx.createBufferSource();
        aud.buffer = audioError;
        aud.connect(audioCtx.destination);
        aud.start(0);
}

This is my code.
After updating to ios 15, it is no longer working. Ios 14 and Android works fine.

I note that it is only compatible with IOS 14.5 is that the problem? - https://developer.mozilla.org/en-US/docs/Web/API/AudioContext

**Comment by Jcarloscosta** [comment] 2022-01-05 12:13
Anyone with the same type of issue? 

I'm using the code in Outsystems

**Comment by queengooborg** [comment] 2022-03-31 12:15
Can you tell us what the problem is in the first place, though?  Are you getting some sort of error message, or...?

Code examples are helpful, but without knowing what we're looking for, we won't be able to figure out what to put into the compatibility data.

**Comment by cookiengineer** [comment] 2022-04-10 18:32
The problem he is referring to is that Safari does not support the specified `AudioContext` API. I came here because the data being used for `canisue.com` is incorrectly labeling Safari as having full support of the API.

https://github.com/mdn/browser-compat-data/blob/main/api/AudioContext.json

@Jcarloscosta Did you take a look at the [Migrating from webkitAudioContext](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Migrating_from_webkitAudioContext) article on MDN?

I'm currently in the process of re-developing a project I've made, because the Safari I'm using on the iOS device doesn't work with the standard WebAudio APIs.

Maybe you can also take a look at WebKit's WebAudio test suite in order to figure out their expectations of how APIs are used and what is the difference to your code? So far, I thought this approach works for me; but I came here to file about the wrong AudioContext.json data, because it is labelled as Safari supporting all standard APIs, which it seemingly does not.

WebKit's WebAudio API test folder for reference: https://github.com/WebKit/WebKit/tree/main/LayoutTests/webaudio

**Comment by queengooborg** [comment] 2022-04-10 18:58
As our data indicates, which can be seen on the corresponding MDN article, Safari and Safari iOS both support this API and most of its subfeatures.  As an additional note, I've been using the API on my own on many browsers with no issues.

Can you please _describe the problems_ so that we will be able to properly convey them to our users?

(P.S. CanIUse's main entry point, https://caniuse.com/audio-api, does not come from MDN.)

**Comment by sideshowbarker** [comment] 2022-04-11 00:57
What’s needed here is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that includes:

- a description of what the expected behavior should be
- a description of what the actual behavior is
- the exact wording of any error messages

**Comment by queengooborg** [comment] 2023-02-18 09:44
I'm going to close this because has been no explanation of an actual problem or a response in months.

**Closed by queengooborg** 2023-02-18 09:44 UTC
Labels: data:api :rabbit2:, info needed :mag:
