### ISSUE TITLE
css.selectors.-webkit-scrollbar - iOs and scrollbar

### ISSUE THREAD

**Issue by fillika** [mdn/browser-compat-data#10083] opened 2021-04-26 07:23 UTC
Hello!
I found this information in the developer forum. Need to correct info about scrollbar in Safari browser.
https://developer.apple.com/forums/thread/670065

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.-webkit-scrollbar`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar
* Report started: 2021-04-26T07:17:36.508Z

</details>

**Comment by BgeeAudio** [comment] 2021-05-12 10:02
I spent quite sometime trying to find why the scrollbars weren't working on iPhone before finding this thread...

Why would Apple even do this?

**Comment by vinyldarkscratch** [comment] 2021-05-12 10:47
Closing as a duplicate of #9967.

**Closed by vinyldarkscratch** 2021-05-12 10:47 UTC
Labels: data:css :art:
