### ISSUE TITLE
api.Navigator.hardwareConcurrency - Works in Safari

### ISSUE THREAD

**Issue by felix-schindler** [mdn/browser-compat-data#20490] opened 2023-08-06 10:52 UTC
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

For Safari it says that is only has been supported for Version 10.1 (or 10.3 on iOS).

- See https://webkit.org/blog/12176/release-notes-for-safari-technology-preview-138/ "Restored `navigator.hardwareConcurrency`"

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Supported in Safari

### Did you test this? If so, how?

Yes, by running `navigator.hardwareConcurrency` in the console of Safari 16.6 on Mac

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/hardwareConcurrency

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.hardwareConcurrency`
* Report started: 2023-08-06T10:41:08.685Z

</details>

**Comment by queengooborg** [comment] 2023-08-10 02:44
Duplicate of #20429.

**Closed by queengooborg** 2023-08-10 02:44 UTC
Labels: data:api :rabbit2:, needs triage 🔎
