### ISSUE TITLE
api.Bluetooth.getAvailability - Not working in Chrome Android

### ISSUE THREAD

**Issue by Suhan999** [mdn/browser-compat-data#18237] opened 2022-11-18 07:37 UTC
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

   as

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

I use getAvailability in my proect. It is working fine on my computer when I hosted my website. Whenever I tired with my Android Phone it is not working. I updated my chrome. But it was not working on Android

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Bluetooth/getAvailability

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Bluetooth.getAvailability`
* Report started: 2022-11-18T07:16:02.183Z

</details>

**Comment by queengooborg** [comment] 2023-02-09 11:05
This is supported in Chrome Android.  There's not enough actionable information to determine what the issue is, so I'm closing this.

**Closed by queengooborg** 2023-02-09 11:05 UTC
Labels: data:api :rabbit2:, needs triage 🔎
