### ISSUE TITLE
http.methods - Missing PATCH method

### ISSUE THREAD

**Issue by jodydonetti** [mdn/browser-compat-data#23772] opened 2024-07-11 13:20 UTC
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

The browser compatibility table contains all the existing methods listed above, except for the PATCH method.

### What did you expect to see?

The PATCH method listed

### Did you test this? If so, how?

Nothing to test, it's just missing in the table

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.methods`
* Report started: 2024-07-11T13:18:59.168Z

</details>

**Comment by queengooborg** [comment] 2024-07-11 15:05
Duplicate of #15274.

**Closed by queengooborg** 2024-07-11 15:05 UTC

**Comment by jodydonetti** [comment] 2024-07-11 15:24
Dang it, I even searched for it but didn't see it.
