### ISSUE TITLE
http.headers.Access-Control-Allow-Headers - Safari does support setting a wildcard

### ISSUE THREAD

**Issue by royderks** [mdn/browser-compat-data#18841] opened 2023-02-07 11:24 UTC
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Safari says the wildcard is unsupported, but I tested it (see below) and it is supported

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Some sort of error, but it did not fail -- which was unsurprising but good

### Did you test this? If so, how?

Yes, I set up a simple Node Server and client. In Safari 16 I was able to send a request with a custom header `x-my-header` and the CORS request succeeded

### Do you have anything more you want to share?

![CleanShot 2023-02-07 at 12 23 11@2x](https://user-images.githubusercontent.com/10717410/217231966-4829e72b-bf98-4b07-9504-ded647ac09a1.png)

<img width="324" alt="CleanShot 2023-02-07 at 12 23 31@2x" src="https://user-images.githubusercontent.com/10717410/217231981-a9158804-de01-4fff-8e48-064c4993aef7.png">

Bug report for Safari WebKit that solves the issue of not supporting the wildcard (is fixed now) https://bugs.webkit.org/show_bug.cgi?id=165508

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Access-Control-Allow-Headers`
* Report started: 2023-02-07T11:11:29.035Z

</details>

**Comment by claudepache** [comment] 2023-02-10 23:44
Duplicate of #11232

**Closed** 2023-08-09 17:32 UTC
Labels: data:http :mountain_cableway:, needs triage 🔎
