### ISSUE TITLE
Add "bugs" field to features, to allow lookup of bug information

### ISSUE THREAD

**Issue by a2sheppy** [mdn/browser-compat-data#1185] opened 2018-02-23 17:22 UTC
We often have to include information about bugs in the compatibility data for given features. A common approach currently is to just include that information in the "notes" field. But that's imprecise and makes it hard to associate the bugs with versions in which they were introduced and/or fixed.

I propose the addition of a new "bugs" record, which would look something like this:

```
"firefox": {
  "version_added": "25",
  "bugs": [
    {
      "id": "2231143",
      "version_added": "25",
      "version_fixed": "28",
      "note": "Until version 28, this property returned a value one lower than it should have."
    }
  ]
}
```

The `"version_fixed"` can also accept a value of `false` to indicate that the bug hasn't been fixed yet (`false` would be the default value, so that omitting `version_fixed` would indicate the bug is still present).

As a corollary to this, I also suggest amending `browsers-schema.json` for the browser data like this:

```
    "browser_statement": {
      "type": "object",
      "properties": {
        "bug_url": { "type": "string", "format": "uri" },
        "releases": {
          "type": "object",
          "additionalProperties": { "$ref": "#/definitions/release_statement" }
        }
      },
      "required": ["releases"],
      "additionalProperties": false
    },
```

Note the addition of the once-per-browser entry `"bug_url"`. This would contain a string with a slow to insert a bug number to generate the URL for a given bug. The syntax could be the same as the one we use for search keywords: `"https://bugdatabase.tld/getbug?id=%s"`, where the `"%s"` gets replaced with the bug number to generate the URL for that bug.

By having the bug information available in the JSON as well as information on how to get links to bugs, we don't have to embed bug links into the notes, but can simply list them in the `"bugs"` section, which gives everything we need to know.

**Comment by jpmedley** [comment] 2018-02-23 18:08
If you don't know, you should ask your engineers how many bugs your browser has open. I'm worried about creating the expectation that MDN is a good place to look for bug information. As much as I wish there were a single place to look up browser bugs, I don't think it's currently achievable. I don't have the resources to document Chromium's issues, and I'm pretty sure I wouldn't get them if I asked.

**Comment by jpmedley** [comment] 2018-02-23 18:18
And a complete bug list isn't something MDN could do anyway since some of the listed browsers are proprietary.

**Comment by wbamberg** [comment] 2018-02-23 18:21
See also https://github.com/mdn/browser-compat-data/issues/126.

**Comment by teoli2003** [comment] 2018-02-26 09:50
As @wbamberg noted, this is a duplicate of issue #126, let's continue the discussion there.

**Closed** 2018-02-26 09:50 UTC
