### ISSUE TITLE
Remove api.Document.contains

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#6841] opened 2020-10-05 22:05 UTC
This feature's MDN URL is a 404, and is assumed to be a duplicate of the inherited `api.Node.contains`.

**Comment by foolip** [comment] 2020-10-06 10:10
Closing as a dupe of https://github.com/mdn/browser-compat-data/issues/6832, sorry I should have linked that in context where I asked about this entry!

**Comment by vinyldarkscratch** [comment] 2020-10-06 10:11
Oops, sorry, forgot to check for duplicates!

**Closed by foolip** 2020-10-06 10:10 UTC
Labels: data:api :rabbit2:
