### ISSUE TITLE
html.elements.input.type_datetime-local - The date is being picjked in mozilla but the time is not on Mozilla ,

### ISSUE THREAD

**Issue by mikeyieldexchange** [mdn/browser-compat-data#21201] opened 2023-11-08 16:21 UTC
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The type is not compatible with mozila firefox 

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

The time should have been picked but didnt

### Did you test this? If so, how?

Yes, used the browers for a project am working on

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.input.type_datetime-local`
* Report started: 2023-11-08T15:35:40.574Z

</details>

**Comment by queengooborg** [comment] 2023-11-08 16:39
Duplicate of #21103 (I think).

**Closed by queengooborg** 2023-11-08 16:39 UTC
Labels: needs triage 🔎
