### ISSUE TITLE
api.Element.scrollTo - Safari does support the `ScrollToOptions` parameter

### ISSUE THREAD

**Issue by mvasigh** [mdn/browser-compat-data#11025] opened 2021-06-14 20:24 UTC
#### What information was incorrect, unhelpful, or incomplete?

It seems that Safari does have support for the `ScrollToOptions` parameter of `Element.scrollTo()`, just not any support for the `"smooth"` value in the `behavior` option. The `api.ScrollToOptions` docs page seems to confirm this, though I'm not sure if there was ever a difference between how `ScrollToOptions` was implemented on the global/window object and the `Element` class in Safari that led 

#### What did you expect to see?

Safari to be listed as having partial support for `ScrollToOptions`, instead of no support.

#### Did you test this? If so, how?

Tested in Safari 14.1.1 using the object API for `Element.scrollTo({ top: number, left: number, behavior: 'smooth' })`, confirmed that the element did scroll, just not smoothly. 

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.scrollTo`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo
* Report started: 2021-06-14T16:37:55.852Z

</details>

**Comment by vinyldarkscratch** [comment] 2021-06-14 21:08
Duplicate of #9059.

**Closed by vinyldarkscratch** 2021-06-14 21:08 UTC
