### ISSUE TITLE
javascript.builtins.Intl.DateTimeFormat.DateTimeFormat - Incomplete support table

### ISSUE THREAD

**Issue by pastinepolenta** [mdn/browser-compat-data#22640] opened 2024-03-15 16:20 UTC
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Many date-time component options are documented in the page but not in the compatibility table. 
For example `options.hour`, `options.timeZoneName`...

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

A complete compatibility table to understand what options are supported and what options aren't

### Did you test this? If so, how?

Certain options don't work on Chrome, certain other do

### Do you have anything more you want to share?

In the "try it" section you can reproduce by adding an unsupported option (like timeZoneName) and you get an error "Error: Invalid option : option"

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Intl.DateTimeFormat.DateTimeFormat`
* Report started: 2024-03-15T16:11:49.966Z

</details>

**Comment by pastinepolenta** [comment] 2024-03-15 16:21
Edited the title

**Comment by Josh-Cena** [comment] 2024-06-21 15:14
Duplicate of https://github.com/mdn/browser-compat-data/issues/19211

**Closed** 2024-06-21 15:16 UTC
Labels: duplicate, data:js
