### ISSUE TITLE
html.elements.dialog - Safari Compatibility

### ISSUE THREAD

**Issue by HCLarsen** [mdn/browser-compat-data#8658] opened 2021-01-05 20:00 UTC
Compatibility for the Safari browser and iOS Safari browser. I tested the dialog element on both, and found that it does display the element. Although there are some unusual behaviours with it displaying it as inline instead of block when the position property is set to relative.

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.dialog`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
* Report started: 2021-01-05T19:40:39.425Z

</details>

**Comment by ddbeck** [comment] 2021-01-20 13:01
Thanks for reporting this, @HCLarsen. Unfortunately, I wasn't able to reproduce this or find evidence that Safari has implemented the `dialog` element. For example, when I tried using the element in Safari, the DOM object was an `HTMLUnknownElement`. It looks to me that Safari is handling the element as if it were any other unknown element.

Since this is consistent with our existing data, I'm going to close this issue. Thank you!

**Closed by ddbeck** 2021-01-20 13:01 UTC
Labels: data:html :page_facing_up:
