### ISSUE TITLE
css.properties.word-break - not supported by edge 

### ISSUE THREAD

**Issue by wanbinkimoon** [mdn/browser-compat-data#9506] opened 2021-03-18 14:27 UTC
#### What information was incorrect, unhelpful, or incomplete?
It seems from my experience that ms edge do not support this property

#### What did you expect to see?
MS edge as not suppoted browser 

#### Did you test this? If so, how?
Tested on Win 10 ms edge 

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.word-break`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
* Report started: 2021-03-18T14:26:34.290Z

</details>

**Comment by ddbeck** [comment] 2021-03-25 10:34
Hi @wanbinkimoon and thanks for reporting this issue.

Unfortunately, I was not able to reproduce this problem. For example, the interactive example on https://developer.mozilla.org/en-US/docs/Web/CSS/word-break works properly in Edge.

I'm going to close this issue. If you still think there's a problem, then please follow up with sample code, screenshots, and browser versions used to verify.

Thank you!

**Closed by ddbeck** 2021-03-25 10:34 UTC
Labels: data:css :art:, wontfix :-1:

**Comment by wanbinkimoon** [comment] 2021-03-25 10:38
Sorry my issue was quite unclear, as you can see from here: https://caniuse.com/mdn-css_properties_word-break_break-word
only the `break-word` value is not supported in ms edge <= 12

**Comment by ddbeck** [comment] 2021-03-29 14:13
@wanbinkimoon Thanks for the update! I've confirmed our data and it reports (correctly) that it's supported on from version 79 and later. 👍
