### ISSUE TITLE
html.elements.a - Possible missing information regarding the ping attribute in Chrome

### ISSUE THREAD

**Issue by schalkneethling** [mdn/browser-compat-data#10158] opened 2021-04-28 18:01 UTC
#### What information was incorrect, unhelpful, or incomplete?

For the `ping` attribute Chrome and Edge(among others) are shown to support this attribute. For Firefox it is stated that it is behind a flag.

I created a little expressjs app to test the behavior of `ping` and found that it is not being sent in Chrome. I know my code works because when I flip the switch in `about:config` in Firefox the call is made and I can see my code log the following for example:

```
console.log(`origin: ${req.get("ping-from")}`);
console.log(`destination: ${req.get("ping-to")}`);
```

#### What did you expect to see?

Expected the code to work in Chrome as there is no mention of a flag.

#### Did you test this? If so, how?

https://github.com/schalkneethling/using-ping-attribute

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.a`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
* Report started: 2021-04-28T17:23:34.531Z

</details>

**Comment by schalkneethling** [comment] 2021-04-28 18:04
I can confirm that this works in Safari and Edge Dev edition on Mac without any flag wrangling.

**Comment by ddbeck** [comment] 2021-04-28 19:11
Hey @schalkneethling, what version of Chrome were you using? I tested with Chrome as my baseline when I worked on https://github.com/mdn/browser-compat-data/pull/9470 a couple of weeks ago. (I wasn't able to reproduce your problem with my test case, though I haven't tried your app yet.)

**Comment by ddbeck** [comment] 2021-04-28 19:12
Also related: https://github.com/mdn/browser-compat-data/pull/9839

**Comment by schalkneethling** [comment] 2021-04-29 03:17
> Hey @schalkneethling, what version of Chrome were you using? I tested with Chrome as my baseline when I worked on #9470 a couple of weeks ago. (I wasn't able to reproduce your problem with my test case, though I haven't tried your app yet.)

I used 90.0.4430.85 (Official Build) (x86_64) as well as Canary (92)

Also, the sample app only listens for `POST` as that is what the spec states it will send and does for the other browsers tested. Discussion happening here as well https://dev.to/madsstoumann/google-tracking-and-the-ping-attribute-41d5/comments

Thanks for looking into this @ddbeck

**Comment by schalkneethling** [comment] 2021-04-29 03:33
Tried it again with a different profile in Chrome and it works. 🤷‍♂️ I have no idea what is different between the profiles also, I surely have a different profile in Canary?

I thought it might be Privacy Badger, but nope. Bizare. Alas, I believe the conclusion is that it does work by default in Chrome.

**Comment by dontcallmedom** [comment] 2021-04-29 05:59
https://wpt.fyi/results/html/infrastructure/urls/resolving-urls/query-encoding/navigation.sub.html%3Fencoding%3Dutf8?label=experimental&label=master&aligned supports that conclusion

**Comment by ddbeck** [comment] 2021-04-29 09:49
Weird that it did the same thing on both Chrome and Canary. Spooky!

Thanks for updating this, @schalkneethling. I'll close this for now—since it doesn't seem like any data needs to change now—but we can reopen (or start a new issue) if new information comes to light.

**Closed by ddbeck** 2021-04-29 09:49 UTC
Labels: data:html :page_facing_up:
