### ISSUE TITLE
css.types.global_keywords.revert-layer - Chrome does support revert-layer keyword but the MDN table says that it doesn't

### ISSUE THREAD

**Issue by internetword** [mdn/browser-compat-data#22673] opened 2024-03-20 13:44 UTC
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

In the table, it is written that Chrome doesn't support the `revert-layer` keyword. 

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

I was expecting to see Yes in the table.

### Did you test this? If so, how?

I tested it on Chrome 122.0.6261.118 and it worked correctly. I open the devTools just too be sure and there was indeed a checkmark before the css declaration with the keyword.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/revert-layer

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.types.global_keywords.revert-layer`
* Report started: 2024-03-20T13:25:49.998Z

</details>

**Comment by internetword** [comment] 2024-03-20 13:50
I'm definitely not a spammer.

**Comment by queengooborg** [comment] 2024-03-20 15:54
Thanks for updating the title!  We get a LOT of spam issues in this repository, and most leave the title unchanged from the default since a bot/spammer wouldn't need to alter an already "allowed" value.

**Comment by queengooborg** [comment] 2024-06-20 20:08
I just noticed that this is a duplicate of #16336, so I'm going to close this in favor of the earlier issue!

**Closed by queengooborg** 2024-06-20 20:08 UTC
Labels: data:css :art:
