### ISSUE TITLE
api.GPU - Safari Technology Preview supports WebGPU

### ISSUE THREAD

**Issue by quinton-ashley** [mdn/browser-compat-data#23867] opened 2024-07-19 17:41 UTC
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The compatibility table doesn't list Safari "TP" support like on other pages.

Safari Technology Preview does have support for WebGPU.
https://webkit.org/blog/14879/webgpu-now-available-for-testing-in-safari-technology-preview/

Support is also available in iOS Safari under a flag in iOS 17.4 as well, confirmed by an Apple employee.
https://forums.developer.apple.com/forums/thread/748141
https://www.webgpuexperts.com/eu-dma-ios-liberation-webgpu-impact

### What did you expect to see?

Just as Firefox "Nightly" support is listed, Safari "TP" should be as well.

I want devs to know that broad support for webgpu is (hopefully) coming soon! :)

### Did you test this? If so, how?

Yes I've used WebGPU in Safari TP. 

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Many other webgpu feature docs could be updated as well.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebGPU_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.GPU`
* Report started: 2024-07-19T17:29:39.306Z

</details>

**Comment by queengooborg** [comment] 2024-07-20 01:18
Duplicate of #22949.

**Closed by queengooborg** 2024-07-20 01:18 UTC
