### ISSUE TITLE
Write guide to finding compatibility data

### ISSUE THREAD

**Issue by a2sheppy** [mdn/browser-compat-data#3226] opened 2018-12-18 16:53 UTC
We need a nice guide to how to find details of compatibility for each of the major browsers. Not just where the information is but how to correlate a given bug or patch or PR to the release that first included it. Information about useful tools (both online and downloadable). Stuff like that. A contributor should be able to go step-by-step through for each browser and come out the other end with correct compatibility data.

For that matter, someone wanting to build tools to help automate things or speed up the workflow should be able to use this as a guide to where to pull information and how to correlate it until the result is a version number.

I'd like to work on this; I've done a lot of exploring and have some pretty good info. Obviously there will be a lot to be gained from other contributors and there's certainly more to find out there, too.

**Comment by Elchi3** [comment] 2020-03-24 14:45
Duplicate of https://github.com/mdn/sprints/issues/963

**Closed by Elchi3** 2020-03-24 14:45 UTC
Labels: docs :writing_hand:
