### ISSUE TITLE
api.Element.dblclick_event - Supported on Chrome Android

### ISSUE THREAD

**Issue by LXYan2333** [mdn/browser-compat-data#11262] opened 2021-06-26 13:42 UTC
#### What information was incorrect, unhelpful, or incomplete?
chrome Android is compatible with **[Element: dblclick event](https://developer.mozilla.org/en-US/docs/Web/API/Element/dblclick_event)**

#### What did you expect to see?
chrome Android is compatible with Element: dblclick event

#### Did you test this? If so, how?
Install chrome android (chrome 81.0.4044.117) on my Android phone, open [this page](https://developer.mozilla.org/en-US/docs/Web/API/Element/dblclick_event) and double tap the test card. 

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.dblclick_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/dblclick_event
* Report started: 2021-06-26T13:33:44.542Z

</details>

**Comment by vinyldarkscratch** [comment] 2021-07-26 03:43
Closing as a duplicate of #8904.

**Closed by vinyldarkscratch** 2021-07-26 03:43 UTC
Labels: data:api :rabbit2:
