### ISSUE TITLE
Android Webview versions should be given in Chrome release numbers, not Android release numbers.

### ISSUE THREAD

**Issue by jpmedley** [mdn/browser-compat-data#291] opened 2017-07-18 16:22 UTC
As shown by our [Chrome Platform Status entries](https://www.chromestatus.com/features), no web feature added to Webview is given in terms of Android version. This is because [since Android L](https://developer.chrome.com/multidevice/webview/overview) the Webview updates on an approximate six week cycle in lockstep with the Chrome version.

I realize there's no easy solution to this problem. It will take considerable time for me (a Google employee) to update every reference to Webview in this database and on MDN.

What I'm asking is that you consider a Travis test forces (blocking) or encourages (non-blocking) using the correct form of Webview version number. Perhaps this solution could be generalized to encourage or enforce proper data in all browser versions and the rules could be stored in one or more JSON files so that browser vendors could update them as needed.

**Comment by Elchi3** [comment] 2017-07-19 08:04
Yes, we have thought about this, too. Validating versions is very much needed.

I think this is a duplicate of #168 where we started to collect valid browser versions. We still need to figure out how to actually validate this (either using JSON schema techniques or writing a custom validation script).

**Closed** 2017-07-19 13:49 UTC
