### ISSUE TITLE
.scrollTo() isn't supported on Safari

### ISSUE THREAD

**Issue by ChiefChippy2** [mdn/browser-compat-data#3298] opened 2019-01-16 17:45 UTC
`.scrollTo()` isn't supported in iOS Safari. Please change the compatibility.

**Comment by vinyldarkscratch** [comment] 2019-02-02 01:15
Typically a pull request is more helpful than an issue in these cases.  Just submitted a PR myself that fixes it.  :wink:

**Comment by ddbeck** [comment] 2019-02-04 11:31
@vinyldarkscratch it's OK top open issues reporting on data problems. PRs are often faster, but often people see that there's a problem with the data but don't have the supporting details to substantiate that for a PR.

Also, it helps to link to your PRs, if they're responding to a specific issue. That doesn't seem to have happened yet, in this case. Thank you!

**Comment by vinyldarkscratch** [comment] 2019-02-04 17:39
I closed the PR (#3369) because I wanted to do a little research on the matter first, before applying any fixes.  (Most of my efforts have been fixed on the linters, of course.  😛)  Once I'm finished browsing around, I'll re-open it!

**Comment by vinyldarkscratch** [comment] 2019-04-17 08:35
Took a lot longer than expected to get to this, but this has been disconfirmed via manual review.  `window.scrollTo()` is supported on iOS Safari (I've used it in my web development before).

<img width="1112" alt="Screen Shot 2019-04-17 at 01 32 27" src="https://user-images.githubusercontent.com/5179191/56273060-d96fbc80-60b0-11e9-9f2e-73794a3cd07e.png">

![IMG_4087](https://user-images.githubusercontent.com/5179191/56273095-ebe9f600-60b0-11e9-914c-0a626d99455f.png)

**Closed by vinyldarkscratch** 2019-04-17 08:35 UTC
Labels: invalid :no_entry_sign:, wontfix :-1:, data:api :rabbit2:
