### ISSUE TITLE
Issue with "Intl.NumberFormat() constructor": (narrowSymbol not supported on Safari)

### ISSUE THREAD

**Issue by cgarrovillo** [mdn/browser-compat-data#9319] opened 2021-03-01 03:45 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat

#### What information was incorrect, unhelpful, or incomplete?
The incompatibility table does not warn that narrowSymbol is not a valid option for Intl.NumberFormat

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#browser_compatibility

#### What did you expect to see?
A warning for narrowSymbol incompatibility

#### Did you test this? If so, how?
Visited the website

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/numberformat/numberformat`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/numberformat/numberformat/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by sideshowbarker** [comment] 2021-03-03 04:49
OK, I’ve transferred this to the BCD repo, since that’s where we need to make a change.

@cgarrovillo Thanks yeah, using he https://github.com/cgarrovillo/MDN-Intl.NumberFormat/tree/main document, I’ve also reproduced this and confirmed in my environment that Safari 14 reports an error.

Interestingly, though, Safari Technology Preview (Release 119 (Safari 14.1, WebKit 16611.1.10.1)) doesn’t report an error. https://trac.webkit.org/changeset/266031/webkit shows that `narrowSymbol` support was added 2020-08-22. And Safari 14 was released less than a month later, 2020-09-16 — so the Safari 14 release branch was cut before this change went into the trunk.

So we should document this in BCD by marking the Safari support with `partial_implementation` and a note.

@cgarrovillo Do you want to take a shot at writing up patch/PR for that? (If not, I can do it.)

I guess one of us should also raise an issue at https://github.com/tc39/test262/issues

**Comment by cgarrovillo** [comment] 2021-03-04 01:29
I could raise this issue over at test262.

**Comment by sideshowbarker** [comment] 2021-03-07 04:35
OK, I’ve opened #9371 with an update for this.

**Closed** 2021-03-19 12:47 UTC
Labels: data:js :pager:
