### ISSUE TITLE
Add <noframes> element to browser-compat-data

### ISSUE THREAD

**Issue by a2sheppy** [mdn/browser-compat-data#850] opened 2018-01-17 15:34 UTC
The `<noframes>` element is not included and should be. It's obsolete but still needs information provided.

**Comment by Elchi3** [comment] 2018-01-17 15:44
Duplicate of https://github.com/mdn/browser-compat-data/issues/698 which has a PR merged in https://github.com/mdn/browser-compat-data/pull/839. Will be released this week.

**Closed by Elchi3** 2018-01-17 15:44 UTC
