### ISSUE TITLE
http.methods - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by jeff-burgess** [mdn/browser-compat-data#18135] opened 2022-11-03 18:49 UTC
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

The Browser Compatibility table doesn't include a row for the PATCH method.

### What did you expect to see?

Compatibility info for PATCH

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.methods`
* Report started: 2022-11-03T18:33:05.054Z

</details>

**Comment by queengooborg** [comment] 2022-11-03 22:47
Duplicate of #15274.

**Closed by queengooborg** 2022-11-03 22:47 UTC
Labels: data:http :mountain_cableway:
