### ISSUE TITLE
api.Navigator.canShare - <WebShare API is not supported on a iOS 15.2 Safari >

### ISSUE THREAD

**Issue by sayinserdar** [mdn/browser-compat-data#14163] opened 2021-12-26 13:54 UTC
I'm testing WebShareAPI on my iPhone XR with Safari version 15.2

#### What information was incorrect, unhelpful, or incomplete?
The browser compatibility table says that safari supports it but I can't seem the make it work. Same code works fine on macOS Safari but don't work on my iPhone.

#### What did you expect to see?
Web Share Api to work on iOS

#### Did you test this? If so, how?
macOS
![Screenshot 2021-12-26 at 16 53 12](https://user-images.githubusercontent.com/26919126/147410221-266bd919-f1c8-4e35-afa2-98634fde7a55.png)
iOS
![Screenshot 2021-12-26 at 16 53 02](https://user-images.githubusercontent.com/26919126/147410223-9aba1e33-1a95-40b0-8308-0451e8110d2c.png)

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.canShare`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Share_API
* Report started: 2021-12-26T13:47:55.284Z

</details>

**Comment by queengooborg** [comment] 2021-12-27 00:17
Duplicate of #12396.

**Closed by queengooborg** 2021-12-27 00:17 UTC
