### ISSUE TITLE
api.FormData - textarea with hardwrapping are not wrapped in FireFox

### ISSUE THREAD

**Issue by dnouls** [mdn/browser-compat-data#15838] opened 2022-04-15 06:19 UTC
While the API is fully supported on FireFox, it does not fully work correctly. So I think a note should be added to the compatibility of Firefox.

If you have a form configured with hardwrapping and you create the FormData, the textarea contents are not wrapped as is visible on the screen. This works on Chrome/Edge, but not FireFox.

<details>
<summary>MDN page report details</summary>

* Query: `api.FormData`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FormData
* Report started: 2022-04-15T06:16:03.424Z

</details>

**Comment by queengooborg** [comment] 2023-08-08 14:04
Technically a duplicate of #10164 as it also talks about the `hard` value not being supported in Firefox.

**Closed by queengooborg** 2023-08-08 14:04 UTC
Labels: data:api :rabbit2:
