### ISSUE TITLE
api.GlobalEventHandlers.onclick - <onclick needs to be double clicked in Chrome browser for login page>

### ISSUE THREAD

**Issue by vkddhiman** [mdn/browser-compat-data#16053] opened 2022-04-28 07:57 UTC
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `api.GlobalEventHandlers.onclick`
* MDN URL: https://developer.mozilla.org/en-US/docs/web/api/globaleventhandlers/onclick
* Report started: 2022-04-28T07:55:43.881Z

</details>

**Comment by queengooborg** [comment] 2022-04-28 08:03
This issue was closed because it appears to be empty. The issue is not different from the issue template and no actionable information has been provided.

If this has been closed in error, edit the title and body, and post a follow-up comment.

**Closed by queengooborg** 2022-04-28 08:03 UTC
