### ISSUE TITLE
css.properties.font-synthesis : none not working correctly in Chrome 110

### ISSUE THREAD

**Issue by dgibson666** [mdn/browser-compat-data#19062] opened 2023-03-06 15:22 UTC
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

font-synthesis: none is clearly working in Firefox, but all of the demos on the page are incorrectly still showing bold and italics when using Chrome 110.0.5481.178 (Official Build) (64-bit), which leads me to believe this property is not implemented or had a recent regression since the compatibility charts says it was supported back in Chrome 97.

### What browsers does this problem apply to, if applicable?

Chrome

### What did you expect to see?

No bold or italics when the value of none is specified.

### Did you test this? If so, how?

Visually compared results between Chrome 110 and Firefox 110

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/font-synthesis

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.font-synthesis`
* Report started: 2023-03-06T15:01:12.720Z

</details>

**Comment by dgibson666** [comment] 2023-03-06 16:57
Tested in a separate page in Chrome, so this seems to be an issue with MDN's page/iframes that's related to Chrome. MDN page and demos for this CSS property work fine in Firefox.

**Comment by herrernst** [comment] 2023-05-16 10:59
I can confirm that `font-synthesis: none` has no effect on Chrome 113/macOS 13.3. If I open the MDN example in a [separate page](https://interactive-examples.mdn.mozilla.net/pages/css/font-synthesis.html), I still get fake styles with `none`.

**Comment by queengooborg** [comment] 2023-08-09 18:22
Duplicate of #18925.

**Closed by queengooborg** 2023-08-09 18:22 UTC
Labels: data:css :art:, needs triage 🔎
