### ISSUE TITLE
A dedicated field for tracking bugs?

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#7373] opened 2020-11-16 18:56 UTC
`notes: "See <a href='https://bugzil.la/1234567'>bug 1234567</a>."` is quite verbose, could we add a `tracking_bug` field and automatically generate the sentence in MDN?

**Comment by vinyldarkscratch** [comment] 2020-11-16 19:19
Duplicate of #126.

**Closed by vinyldarkscratch** 2020-11-16 19:19 UTC
