### ISSUE TITLE
api.Notification - Chrome Android constructor compatibility is inaccurate

### ISSUE THREAD

**Issue by bh3605** [mdn/browser-compat-data#9766] opened 2021-04-05 14:41 UTC
#### What information was incorrect, unhelpful, or incomplete?
Chrome Android constructor compatibility is inaccurate. That platform does support the Notification API, however, it does not support the original constructor. Which makes the support level very much in limbo. The API exists, but you can't instantiate it using `new Notification("title")`. The Google team says they aren't deprecating or removing the API. It's recommended to use a service worker. Through all the chatter it comes out that using a service worker is very much akin to using a sledgehammer for a tiny nail, but that's apparently what you're suppose to do or as the developer have your site not use Notifications at all.

Supporting documentation:
https://stackoverflow.com/questions/29774836/failed-to-construct-notification-illegal-constructor
https://github.com/whatwg/notifications/issues/26#issuecomment-126310459
https://bugs.chromium.org/p/chromium/issues/detail?id=481856
https://github.com/dstockwell/chromium/commit/4c1464c869cdb9a40a1d12a0ea2ad9d588ef75aa
https://codereview.chromium.org/920153002

#### What did you expect to see?
Actual recommended use specifies using a service worker.

#### Did you test this? If so, how?
Tested in Android Studio Emulator.
new Notification("notify");
Error displayed is
Uncaught TypeError: Failed to construct 'Notification': Illegal constructor. Use ServiceWorkerRegistration.showNotification() instead.
    at <anonymous>:1:1

<details>
<summary>MDN page report details</summary>

* Query: `api.Notification`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/notification
* Report started: 2021-04-05T14:31:29.461Z

</details>

**Comment by ddbeck** [comment] 2021-04-06 17:06
Thanks for reporting this, @bh3605. This is a duplicate of https://github.com/mdn/browser-compat-data/issues/7923. In that issue, there's some existing discussion of this and other problems with the `Notification` API data for Chrome for Android. I'm going to close this issue as a duplicate of that one, but I've opened a PR, https://github.com/mdn/browser-compat-data/pull/9787, to fix the narrow problem presented here. Thank you!

**Closed by ddbeck** 2021-04-06 17:06 UTC
Labels: data:api :rabbit2:, duplicate :dancing_women:
