### ISSUE TITLE
html.elements.input.type_datetime-local - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by giridharc** [mdn/browser-compat-data#20681] opened 2023-09-11 06:16 UTC
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

<input id="appt-time" type="datetime-local" name="appt-time" step="2" formControlName="startrange"
               [(ngModel)]="selectedstartTime">
            </div>
            
            using this one in my project its working expected in chrome.
            
            now my problem is its not working in firefox 117.0 (64-bit) and Micro soft edge Version 115.0.1901.188.
            can you please help me

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

not working time value showing only date popup

### Did you test this? If so, how?

browser

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.input.type_datetime-local`
* Report started: 2023-09-11T05:31:04.521Z

</details>

**Comment by queengooborg** [comment] 2023-09-11 18:08
Duplicate of #16138 for the most part.

**Closed by queengooborg** 2023-09-11 18:08 UTC
Labels: data:html :page_facing_up:, needs triage 🔎
