### ISSUE TITLE
css.types.color.oklch - Add Chrome 111 and Chromuim browser support

### ISSUE THREAD

**Issue by ai** [mdn/browser-compat-data#18845] opened 2023-02-07 18:44 UTC
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

`oklch()`, `oklab()`, `lch()`, `lab()` supports

### What did you expect to see?

That they will be supported from Chrome 110

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

We can see [ CSS Color Module Level 4](https://chromestatus.com/feature/5147752829288448) (the spec of these functions) in [Chrome roadmap](https://chromestatus.com/roadmap)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklch

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.types.color.oklch`
* Report started: 2023-02-07T18:37:12.195Z

</details>

**Comment by queengooborg** [comment] 2023-02-13 16:21
Duplicate of #18902.

**Closed by queengooborg** 2023-02-13 16:21 UTC
Labels: data:css :art:, needs triage 🔎
