### ISSUE TITLE
Add data guidelines for `spec_url`

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#11216] opened 2021-06-23 15:03 UTC
Now that `spec_url` is in widespread use, it would be nice to have one or more guidelines to setting and maintaining `spec_url` data. I'd like a sense of how to answer questions such as:

- What version of the spec should I use?
- If a feature is plausibly represented in more than one spec, which one do I use or do I use both? When do I use more than one `spec_url`?
- What's the preferred fragment target?
- When a spec isn't represented in w3c/browser-specs, what qualifies a spec for inclusion in our exceptions list?

cc: @Elchi3, @sideshowbarker

**Comment by ddbeck** [comment] 2021-06-23 15:05
@Elchi3 as a narrow part of this, you mentioned you were interested in adding comments to our existing exceptions list. Making that change might help inform some or all of this.

**Comment by sideshowbarker** [comment] 2021-06-28 05:13
Just ACKing this for now — I will make time this week to commenting in substance

**Comment by foolip** [comment] 2021-10-04 09:44
https://github.com/mdn/browser-compat-data/issues/12685 asks what should be done with `standard_track` when there's a `spec_url`.

**Comment by queengooborg** [comment] 2023-07-21 04:10
Closing this as a duplicate of #10106.

**Closed by queengooborg** 2023-07-21 04:10 UTC
Labels: docs :writing_hand:
