### ISSUE TITLE
String.prototype.repeat - IE data incorrect

### ISSUE THREAD

**Issue by Yash-Singh1** [mdn/browser-compat-data#8080] opened 2020-12-21 05:07 UTC
#### What information was incorrect, unhelpful, or incomplete?

IE does support `String.prototype.repeat()`

#### What did you expect to see?

That IE supports it

#### Did you test this? If so, how?

I opened up IE 11 on VMware and tested the following in the developer tools:
```js
'a'.repeat(4);
```
It outputted `"aaaa"`

I am not sure which from which version IE supports `String.prototype.repeat`, I just tested it on IE 11

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat

**Comment by ddbeck** [comment] 2021-01-18 17:29
Thanks for opening this issue, @Yash-Singh1. I tried to find out when this first appeared in IE (whether in 11 or an earlier version) but I wasn't able to reproduce the support that your reported for IE 11. I suspect there might have been a polyfill involved to make this work for you. Whatever the cause, I don't think there's anything to change here right now, so I'm going to close this issue. Thanks again!

**Closed by ddbeck** 2021-01-18 17:29 UTC
Labels: data:js :pager:
