### ISSUE TITLE
api.Clipboard.writeText - <Firefox Developer edition not suported >

### ISSUE THREAD

**Issue by richiwarmen** [mdn/browser-compat-data#9051] opened 2021-02-10 08:10 UTC
#### What information was incorrect, unhelpful, or incomplete?
Firefox list as compatible but is not

#### What did you expect to see?
not compatible..

#### Did you test this? If so, how?
Developer console

Function test
    navigator.permissions.query({name: "clipboard-write"}).then(result => {
        if (result.state === "granted" || result.state === "prompt") {
            /* clipboard permission */
        }
    });
console error: 
Uncaught (in promise) TypeError: 'clipboard-write' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName.

<details>
<summary>MDN page report details</summary>

* Query: `api.Clipboard.writeText`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText
* Report started: 2021-02-10T07:54:43.819Z

</details>

**Comment by ddbeck** [comment] 2021-02-10 09:40
Thanks for reporting this, @richiwarmen. Upon further investigation, it looks like we have correct data. Some details:

- The data for the `"clipboard-write"` permission (see [`Permissions.json`](https://github.com/mdn/browser-compat-data/blob/7ed9748c4eaf10c4e9d7fbdd4ca21caafddf2945/api/Permissions.json#L353)) reports that the permission name is unsupported in Firefox. You can see this [on MDN on the Permissions API page](https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API#browser_compatibility). I was able to reproduce your error to confirm the data.
- The data for the `writeText()` method (see [`Clipboard.json`](https://github.com/mdn/browser-compat-data/blob/166dfbfc58d9522bc01fca0c28e3ba0d0c8883a1/api/Clipboard.json#L268)) reports that the method is supported in Firefox. That's what you saw on [the Clipboard.writeText() page on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText). I was able to confirm that Firefox does in fact support this method.

Since the data checks out, I don't think there's any further action to take on this issue and I'm going to close it. That said, thank you for raising the issue and helping us ensure the quality of the data here.

**Closed by ddbeck** 2021-02-10 09:40 UTC
Labels: wontfix :-1:, data:api :rabbit2:
