### ISSUE TITLE
webextensions.api.userScripts - Add Chrome 120 support

### ISSUE THREAD

**Issue by carterworks** [mdn/browser-compat-data#22207] opened 2024-02-12 20:34 UTC
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Browser compatibility for the userScripts API

### What did you expect to see?

Chrome supported version should be >= 120, but Chrome does not support onBeforeScript or register.cookieStoreId

### Did you test this? If so, how?

Built a barebones Chrome extension withe the `userScripts` permission

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.chrome.com/docs/extensions/reference/api/userScripts

### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/userScripts

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.userScripts`
* Report started: 2024-02-12T20:32:56.910Z

</details>

**Comment by rebloor** [comment] 2024-02-16 15:42
Duplicate of #21922

**Closed by rebloor** 2024-02-16 15:42 UTC
Labels: data:webext :game_die:
