### ISSUE TITLE
Request: Add data for Deno

### ISSUE THREAD

**Issue by 00ff0000red** [mdn/browser-compat-data#8729] opened 2021-01-13 00:48 UTC
Many JavaScript compatibility tables include information for Node.js, a well known server-side JavaScript runtime, but [last year](https://deno.land/posts/v1), [Deno](https://deno.land) was released.
Their team seems to have a strong focus on web compatibility, and they recently [began adding WPT tests](https://github.com/denoland/deno/issues/9001) to ensure/confirm their compatibility with the HTML API specs.

Like Node, could Deno be added to MDN's compat tables?

**Comment by vinyldarkscratch** [comment] 2021-01-13 11:30
This is a duplicate of #5476.  Closing in favor of the existing issue.

**Closed by vinyldarkscratch** 2021-01-13 11:30 UTC
