### ISSUE TITLE
api.HTMLElement.focus - Support matrix needs updating

### ISSUE THREAD

**Issue by NickGard** [mdn/browser-compat-data#14979] opened 2022-02-14 19:52 UTC
#### What information was incorrect, unhelpful, or incomplete?
Safari now supports the `options.preventScroll` argument.

#### What did you expect to see?
The support matrix showing "`options.preventScroll` parameter" as supported in Safari 15.1

#### Did you test this? If so, how?
I tested this on Safari v15.1 (16612.2.9.1.30, 16612) on macOS Big Sur 11.6.1 (20G224). Also, the [linked bug](https://bugs.webkit.org/show_bug.cgi?id=178583) is closed as RESOLVED FIXED.

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLElement.focus`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus
* Report started: 2022-02-14T19:46:07.323Z

</details>

**Comment by queengooborg** [comment] 2022-04-01 17:32
Duplicate of #12925.

**Closed by queengooborg** 2022-04-01 17:32 UTC
Labels: data:api :rabbit2:
