### ISSUE TITLE
iOS version vs iOS Safari version

### ISSUE THREAD

**Issue by takamoso** [mdn/browser-compat-data#5776] opened 2020-03-04 03:43 UTC
For example, CSS `conic-gradient()` data shows support since iOS 12.2.
What's the reason for using not iOS Safari version but iOS version?

https://github.com/mdn/browser-compat-data/blob/7055552acd392bfae2e8d4867fb669aea5c9944e/css/types/image.json#L396-L401

For your reference:

| iOS version | iOS Safari version |
|---|---|
|12.4.1|12.1.2|
|12.4|12.1.2|
|12.3.1|12.1.1|
|12.2|12.1|
|12.1.4|12.0|
|12.1|12.0|
|12.0|12.0|

**Comment by vinyldarkscratch** [comment] 2020-03-04 05:38
We use the iOS version rather than the Safari version per direct request of Apple themselves; see https://github.com/mdn/browser-compat-data/issues/2006#issuecomment-457277312.

(Closing this issue since it's technically a duplicate of #2006.)

**Closed by vinyldarkscratch** 2020-03-04 05:39 UTC
