### ISSUE TITLE
api.BarcodeDetector - Chrome support is platform-dependent

### ISSUE THREAD

**Issue by jimmywarting** [mdn/browser-compat-data#9030] opened 2021-02-07 20:04 UTC
#### What information was incorrect, unhelpful, or incomplete?

The Browser compatibility table shows that chrome v83 supports BarcodeDetector but this was apparently platform dependent 

> This feature depends on built-in face detection support which is only provided by Android* and macOS** at the moment. 
> https://www.chromestatus.com/feature/4757990523535360

#### What did you expect to see?

it was suppressing for me to see and think that chrome did support it on any platform...
I would like to see a Asterisk* symbol or something like partial support for it.

#### Did you test this? If so, how?
Tested it first on mac and android and it did work ok. then when it came to windows then i got a error saying that BarcodeDetector is not defined

<details>
<summary>MDN page report details</summary>

* Query: `api.BarcodeDetector`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/BarcodeDetector
* Report started: 2021-02-07T19:57:28.846Z

</details>

**Comment by ddbeck** [comment] 2021-02-08 17:33
Thanks for reporting this, @jimmywarting. I discovered that this is a duplicate of #7184. I've proposed a way to fix this problem in that issue and I'd welcome a PR from you (or another contributor) making those changes. Thanks again!

**Closed by ddbeck** 2021-02-08 17:33 UTC
Labels: data:api :rabbit2:, duplicate :dancing_women:
