### ISSUE TITLE
http.headers.X-Frame-Options 

### ISSUE THREAD

**Issue by raamvimal** [mdn/browser-compat-data#10677] opened 2021-05-30 14:13 UTC
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.X-Frame-Options`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
* Report started: 2021-05-30T14:07:09.892Z

</details>

**Comment by vinyldarkscratch** [comment] 2021-05-30 20:35
This issue was closed because it appears to be empty. The issue is not different from the issue template and no actionable information has been provided.

If this has been closed in error, edit the title and body, and post a follow-up comment.

**Closed by vinyldarkscratch** 2021-05-30 20:35 UTC
