### ISSUE TITLE
URL constructor has deficiencies in Safari

### ISSUE THREAD

**Issue by dilyanpalauzov** [mdn/browser-compat-data#6749] opened 2020-09-22 20:56 UTC
This does not work with WebKit 2.28.4 / Safari 13:
```javascript
new URL('http://x', undefined)
```
It throws an error, while in Firefox, Chromium, node it does not throw.

https://developer.mozilla.org/en-US/docs/Web/API/URL#Browser_compatibility says URL-constructor+Safari=♡.
 
See also https://bugs.webkit.org/show_bug.cgi?id=216841 and https://github.com/zloirock/core-js/pull/853 .

**Comment by sideshowbarker** [comment] 2020-09-23 04:49
Thanks for catching this.

I’ve confirmed that in Safari 14 (15610.1.28.1.9, 15610) and earlier, `new URL('http://x', undefined)` throws — but it doesn’t throw in current Safari Technology Preview (Release 113, WebKit 15610.2.3.1).

So I’ve raised #6752 to update the Safari data for the URL constructor to note this problem.

**Comment by queengooborg** [comment] 2021-12-24 08:01
Closing since this was taken care of by #6752!

**Closed by queengooborg** 2021-12-24 08:01 UTC
Labels: data:api :rabbit2:
