### ISSUE TITLE
api.Element.scrollIntoView - Options supported by Safari 15.4

### ISSUE THREAD

**Issue by reinhrst** [mdn/browser-compat-data#16159] opened 2022-05-07 09:49 UTC
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Options is (finally) supported by Safari 15.4: https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes (search for "ScrollOptions")

### What browsers does this problem apply to, if applicable?

Safari

### Did you test this? If so, how?

Have the following code working for me locally (on Safari 15.4):

```
      selectedItem.scrollIntoView({block: "nearest"})
```

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.scrollIntoView`
* Report started: 2022-05-07T09:32:07.161Z

</details>

**Comment by queengooborg** [comment] 2022-06-16 00:29
Duplicate of #9055.

**Closed by queengooborg** 2022-06-16 00:29 UTC
Labels: data:api :rabbit2:, needs triage 🔎
