### ISSUE TITLE
api.Element.scrollIntoView - Safari Supports `options`

### ISSUE THREAD

**Issue by jvanderen1** [mdn/browser-compat-data#16691] opened 2022-06-15 23:29 UTC
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

When I invoked `scrollIntoView({block: 'nearest'})` in Safari, it behaved the same way Chrome would.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

I expected Safari to fallback to `scrollIntoView()` behavior (but the current behavior is better).

### Did you test this? If so, how?

I tested it with the following HTML:

```html
<!DOCTYPE html>
<html>
<style>
  #myDIV {
    height: 250px;
    width: 250px;
    overflow: auto;
    background: coral;
  }

  #content {
    margin:500px;
    height: 800px;
    width: 2000px;
    background-color: coral;
  }
</style>

<body>
<h1>The Element Object</h1>
<h2>The scrollIntoView() Method</h2>

<button onclick="myFunction()">Scroll</button>

<p>Click "Scroll" to scroll to the top of the element with id="content".</p>


<div id="myDIV">
  <div id="content">
  <p id="item-1">Some text inside an element.</p>
  <p>Some text inside an element.</p>
  <p>Some text inside an element.</p>
  </div>
</div>

<script>
function myFunction() {
  const element = document.getElementById("item-1");
  element.scrollIntoView({block: "nearest"});
}
</script>

</body>
</html>
```

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.scrollIntoView`
* Report started: 2022-06-15T23:23:23.122Z

</details>

**Comment by queengooborg** [comment] 2022-06-16 00:29
Duplicate of #9055.

**Closed by queengooborg** 2022-06-16 00:29 UTC
Labels: duplicate :dancing_women:, data:api :rabbit2:, needs triage 🔎
