### ISSUE TITLE
Add a field to indicate "this was defined in somewhere else"

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#7400] opened 2020-11-18 15:13 UTC
From https://github.com/mdn/browser-compat-data/pull/7360#discussion_r523448704.

For example, Event.cancelBubble was previously defined in UIEvent, so the current note says:

>Prior to Firefox 53, this property was defined on the <a href='https://developer.mozilla.org/docs/Web/API/UIEvent'><code>UIEvent</code></a> interface. See <a href='https://bugzil.la/1298970'>bug 1298970</a> for more details.

Could we add something like `"alternative_parent": "UIEvent"` to make things less verbose?

Probably also related to mixins.

**Comment by vinyldarkscratch** [comment] 2020-11-18 20:21
This is a duplicate of #3463.

**Closed by vinyldarkscratch** 2020-11-18 20:21 UTC

**Comment by saschanaz** [comment] 2020-11-18 21:31
Always thank you for finding a dupe for me, and sorry for that 🙏

**Comment by vinyldarkscratch** [comment] 2020-11-18 21:32
No worries, it's all good!
