### ISSUE TITLE
svg.elements.title - Chrome and Edge support Tooltip display

### ISSUE THREAD

**Issue by wzhonggo** [mdn/browser-compat-data#16692] opened 2022-06-16 02:49 UTC
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Edge 102 and Chrome 102 support Tooltip display

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `svg.elements.title`
* Report started: 2022-06-16T02:45:33.536Z

</details>

**Comment by queengooborg** [comment] 2023-02-10 13:49
Duplicate of #5893.

**Closed by queengooborg** 2023-02-10 13:49 UTC
Labels: data:svg :paintbrush:, needs triage 🔎
