### ISSUE TITLE
javascript.builtins.String.matchAll - matchAll function compatibility with Node version

### ISSUE THREAD

**Issue by kranthikumariitkgp** [mdn/browser-compat-data#10006] opened 2021-04-21 12:46 UTC
I have NodeJs of version 12.20.1 in my docker container and using matchAll in my code. But it is giving me stack: 'TypeError: something.matchAll is not a function\n'
Here something is my string used.

As per documentation, matchAll function should be compatible with 12.0.0 or above. But i am getting above issue. 
Please help me to resolve.

Thanks

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.String.matchAll`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll
* Report started: 2021-04-21T12:39:56.240Z

</details>

**Comment by jculver050** [comment] 2021-05-10 06:10
Close

**Comment by vinyldarkscratch** [comment] 2021-05-12 10:42
What type of object is that `something` you're mentioning?

**Comment by queengooborg** [comment] 2021-12-24 21:51
Sorry it has taken so long to respond.  I'm unsure what's going on in your code, but this sounds like a development issue.  I've double-checked and confirmed support since at least NodeJS v12.4 (and Node.green indicates results are identical for v12.0 - v12.4, see https://node.green/#ES2020-features-String-prototype-matchAll-basic-functionality).  All I can think of is that your `something` might not be a string.

I'm closing this issue since it's not an issue with our compatibility data.  If you need development help, please refer to a site like StackOverflow.

**Closed by queengooborg** 2021-12-24 21:51 UTC
Labels: data:js :pager:
