### ISSUE TITLE
api.Window.sessionStorage - Safari doesnt support sessionStorage on Duplicate tab

### ISSUE THREAD

**Issue by SebastianGalianoMolina** [mdn/browser-compat-data#22948] opened 2024-04-26 09:42 UTC
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

The page says that Safari has full support for sessionStorage. But sessionStorage defines that on tab duplicate the sessionStorage must be maintained. This is not the case in Safari. 

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

When using sessionStorage on a safari browser tab, and duplicating that tab the sessionStorage should be maintained 

### Did you test this? If so, how?

I tested it by adding things in sessionStorage and then duplicate in safari, chrome and firefox and the behaviour of safari doesn't follow the indication of the documentation

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage

Duplicating a tab copies the tab's sessionStorage into the new tab.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.sessionStorage`
* Report started: 2024-04-26T09:38:41.290Z

</details>

**Comment by skyclouds2001** [comment] 2024-04-26 16:03
see https://github.com/mdn/content/issues/30598#issuecomment-1832088200, this is not a bug, this is just the default behavior - sessionStorage does not shared between different tabs but on same-origin iframes

**Comment by queengooborg** [comment] 2024-06-21 14:26
Duplicate of #21594.

**Closed by queengooborg** 2024-06-21 14:26 UTC
Labels: data:api :rabbit2:
