### ISSUE TITLE
http.status - add status 505-511

### ISSUE THREAD

**Issue by arihant2math** [mdn/browser-compat-data#8692] opened 2021-01-09 23:29 UTC
The compatibility data after errors 504, 425, 308, 226 are not shown, could this be fixed?

<details>
<summary>MDN page report details</summary>

* Query: `http.status`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
* Report started: 2021-01-09T23:27:28.364Z

</details>

**Comment by vinyldarkscratch** [comment] 2021-01-13 00:03
Could you clarify on what HTTP status codes you're looking to have added?

**Comment by arihant2math** [comment] 2021-01-21 21:54
I am looking for 505-511.

**Comment by ddbeck** [comment] 2021-02-02 19:28
Thanks for reporting this, @arihant2math. I think there's some broader questions about filling HTTP status code gaps in BCD, so I opened #8936 to handle this systematically. I'd consider this blocked until we have an answer on the questions raised there, so I'm going to mark this issue as not-ready. Thanks again for the report!

**Comment by jculver050** [comment] 2021-05-10 06:49
Close

**Comment by Elchi3** [comment] 2023-06-09 12:24
Closing as duplicate of https://github.com/mdn/browser-compat-data/issues/8936

**Closed by Elchi3** 2023-06-09 12:24 UTC
Labels: data:http :mountain_cableway:, not ready :no_entry:, idle 🐌
