### ISSUE TITLE
api.Document.hasFocus - Not working on firefox mobile

### ISSUE THREAD

**Issue by AseemRohilla** [mdn/browser-compat-data#9779] opened 2021-04-06 05:01 UTC
Andriod 10 
firefox version 87.0.0-rc.1

#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `api.Document.hasFocus`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/hasFocus
* Report started: 2021-04-06T04:57:35.680Z

</details>

**Comment by ddbeck** [comment] 2021-05-25 14:52
@AseemRohilla thanks for reporting this issue. Using the demo on the MDN page, I was able to successfully demonstrate that `hasFocus()` works on Firefox for Android. Since I was unable to reproduce your problem, I'm going to close this issue. It's possible you've encountered a bug in your own code or a problem with your specific device. That said, thank you for your report—it helps us verify the correctness of our data.

**Closed by ddbeck** 2021-05-25 14:52 UTC
Labels: data:api :rabbit2:
