### ISSUE TITLE
javascript.builtins.Reflect - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by YornQiu** [mdn/browser-compat-data#16356] opened 2022-05-19 02:17 UTC
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

Platforms classes are wrong.
Deno and Node.js should be placed in "server".

### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Reflect

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Reflect`
* Report started: 2022-05-19T02:05:45.642Z

</details>

**Comment by queengooborg** [comment] 2022-05-19 06:11
Duplicate of https://github.com/mdn/yari/issues/6314.

**Closed by queengooborg** 2022-05-19 06:11 UTC
Labels: needs triage 🔎
