### ISSUE TITLE
Documentation Not Clear About String.prototype.startsWith() Support in Android webview

### ISSUE THREAD

**Issue by bassem-mf** [mdn/browser-compat-data#6258] opened 2020-06-07 18:11 UTC
On this page
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith
in the "Browser compatibility" section, it says that String.prototype.startsWith() is supported by Android webview ≤37

Does this mean the function is supported by versions less than or equal to 37 and not supported by later versions? Or maybe the author meant ≥37 ?

**Comment by bershanskiy** [comment] 2020-06-08 07:48
To answer your question, the table means this method was added to WebView no later than 37 (that is, supported by 37 and later versions).

You raise a good point that "≤" might be ambiguous. See #5782 for prior discussion.

**Comment by bershanskiy** [comment] 2020-06-08 07:53
Also, active discussion takes place here: https://github.com/mdn/kumascript/issues/1337

**Comment by bassem-mf** [comment] 2020-06-08 07:54
Thank you so much for the clarification!

**Comment by Elchi3** [comment] 2020-12-11 15:29
Closing as this seems like a duplicate of the mentioned issue(s).

**Closed by Elchi3** 2020-12-11 15:29 UTC
Labels: data:js :pager:
