### ISSUE TITLE
api.Navigator.hardwareConcurrency - wrong Safari compatibility data

### ISSUE THREAD

**Issue by LorenzoBloedow** [mdn/browser-compat-data#20528] opened 2023-08-10 13:28 UTC
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

It says Safari and Safari on iOS don't support `navigator.hardwareConcurrency` but [according to caniuse](https://caniuse.com/hardwareconcurrency) they do support it.

### What did you expect to see?

That Safari supports `navigator.hardwareConcurrency` since 10.1 and Safari on iOS since 10.3

### Did you test this? If so, how?

Nope, I'm just going off caniuse data

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/hardwareConcurrency

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.hardwareConcurrency`
* Report started: 2023-08-10T13:03:45.660Z

</details>

**Comment by queengooborg** [comment] 2023-08-10 21:50
Duplicate of #20429.

**Closed** 2023-08-10 21:50 UTC
Labels: needs triage 🔎
