### ISSUE TITLE
api.HTMLElement.pointerdown_event - Safari support is incorrect

### ISSUE THREAD

**Issue by tombigel** [mdn/browser-compat-data#9248] opened 2021-02-24 14:09 UTC
#### What information was incorrect, unhelpful, or incomplete?
Safari support for all Pointer Events (pointerdown, pointerup, pointermove) on some pages
#### What did you expect to see?
Safari 13 and up (And ios safari 13)
#### Did you test this? If so, how?
yes, on Safari 14 on my Mac I tried a working demo (internal at work, sorry, can't share)
Also, in some pages the documentation is correct (for onpointerdown for example)

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLElement.pointerdown_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/pointerdown_event
* Report started: 2021-02-24T13:58:58.245Z

</details>

**Comment by ddbeck** [comment] 2021-03-15 12:28
Thanks for reporting this, @tombigel! This is a duplicate of #8709, which is meant to cover all the pointer events, so I'm going to close this issue. I also expect that #9455 will fix the specific events you've mentioned very soon. Thank you!

**Closed by ddbeck** 2021-03-15 12:28 UTC
Labels: data:api :rabbit2:, duplicate :dancing_women:
