### ISSUE TITLE
api.ParentNode.replaceChildren - now supported in Safari

### ISSUE THREAD

**Issue by zuzusik** [mdn/browser-compat-data#8939] opened 2021-02-03 03:15 UTC
#### What information was incorrect, unhelpful, or incomplete?

This method is now supported in Safari (checked on version 14.0.2) 

#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `api.ParentNode.replaceChildren`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/replaceChildren
* Report started: 2021-02-03T03:12:25.311Z

</details>

**Comment by ddbeck** [comment] 2021-02-04 17:50
Thanks for reporting this, @zuzusik. This is a duplicate of https://github.com/mdn/browser-compat-data/issues/8145. Please see that issue for next steps. Thank you!

**Closed by ddbeck** 2021-02-04 17:50 UTC
Labels: data:api :rabbit2:, duplicate :dancing_women:
