### ISSUE TITLE
webextensions.api.permissions.request - Should actually work on Android since "some version".

### ISSUE THREAD

**Issue by M-Reimer** [mdn/browser-compat-data#21788] opened 2023-12-31 11:47 UTC
### What type of issue is this?

Incorrect support data

### What information was incorrect, unhelpful, or incomplete?

The page tells that "permissions.request()" is not compatible with Firefox on Android.

### What did you expect to see?

Starting with "some version" it has to be compatible. I tried. It works.

### Did you test this? If so, how?

I tried with "Nightly" on Android and "permissions.request" popped up a dialog box and allowed to grant the permission.

### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/request

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.permissions.request`
* Report started: 2023-12-31T11:44:37.012Z

</details>

**Comment by queengooborg** [comment] 2024-01-01 02:44
Nightly usually has new features enabled that aren't enabled in the stable release.  Have you tried the same method in FxA stable?

**Comment by M-Reimer** [comment] 2024-01-01 11:44
I just tested and works on "regular Firefox", too.

I use this feature in this Add-on: https://addons.mozilla.org/de/firefox/addon/togglereferrer/

If you enable the "optional spoofing feature" in the Add-on settings, then the Add-on requests all_url permission.

I don't know where to search to find out when this was implemented.

**Comment by rebloor** [comment] 2024-01-01 17:33
Duplicate of #21704

**Closed by rebloor** 2024-01-01 17:33 UTC
Labels: data:webext :game_die:, info needed :mag:
