### ISSUE TITLE
sticky is not supprot in chrome

### ISSUE THREAD

**Issue by zyxm5** [mdn/browser-compat-data#9591] opened 2021-03-24 14:18 UTC
Google Chrome,87.0.4280.66

#### Did you test this? If so, how?
yes

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.position`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/position
* Report started: 2021-03-24T14:08:50.048Z

</details>

**Comment by ddbeck** [comment] 2021-03-24 22:10
Thanks for reporting this, @zyxm5.

Unfortunately, I was not able to reproduce this. For example, if I select the `sticky` entry in the interactive example on https://developer.mozilla.org/en-US/docs/Web/CSS/position, the scroll the inset content, the box remains stuck to the top.

I am going to close the issue now. But if you have more information to support this (example: a Chromium bug link), then post a follow-up message. Either way, thank you!

**Closed by ddbeck** 2021-03-24 22:10 UTC
Labels: invalid :no_entry_sign:, data:css :art:
