### ISSUE TITLE
api.Navigator.share - Supported on FIrefox Android

### ISSUE THREAD

**Issue by gocher68** [mdn/browser-compat-data#8879] opened 2021-01-27 19:16 UTC
#### What information was incorrect, unhelpful, or incomplete?
Firefox on Android 85.1.0 supports api.Navigator.share

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.share`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share
* Report started: 2021-01-27T19:11:19.291Z

</details>

**Comment by ddbeck** [comment] 2021-01-29 19:41
Thanks for reporting this issue, @gocher68. This appears to be a duplicate of #8833. I'm going to close this one in favor of the other. Thanks again!

**Closed by ddbeck** 2021-01-29 19:41 UTC
Labels: data:api :rabbit2:, duplicate :dancing_women:
