### ISSUE TITLE
webextensions.api.windows - No mention of limits on API Availability

### ISSUE THREAD

**Issue by randycasburn** [mdn/browser-compat-data#8906] opened 2021-01-30 17:58 UTC
Related:  https://github.com/mdn/browser-compat-data/issues/8905#issue-797487304

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.windows`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows
* Report started: 2021-01-30T17:56:11.210Z

</details>

**Comment by vinyldarkscratch** [comment] 2021-05-12 10:13
Closing as a duplicate of #8905, and renamed that PR to cover all of `windows.*` (which'll include `WindowState`).

**Closed by vinyldarkscratch** 2021-05-12 10:13 UTC
Labels: data:webext :game_die:
