### ISSUE TITLE
version_removed meaning

### ISSUE THREAD

**Issue by rebloor** [mdn/browser-compat-data#4827] opened 2019-09-16 18:35 UTC
We tend to define removed features along the lines of "removed in version 70" to mean that the feature worked in version 69 and was taken out, and no longer works, in version 70.
If I define this in the compatibility data as:
```
                  "version_added": 55,
                  "version_removed": "70",
```
This is displayed in the compatibility table on MDN as  "55 – 70", which I would interpret as meaning the features available in version 55 up to and including version 70.

Therefore, should `version_removed` be stated as "the last version in which this feature was available" and in this case state it as "69" so it displays on MDN as "55-69"?

FYI @Elchi3 @ddbeck

**Comment by vinyldarkscratch** [comment] 2019-09-16 20:29
This is a duplicate of #4206 -- please check there for more info!

**Closed by vinyldarkscratch** 2019-09-16 20:29 UTC
