### ISSUE TITLE
api.Window.opener 

### ISSUE THREAD

**Issue by thunder2560** [mdn/browser-compat-data#9150] opened 2021-02-17 03:34 UTC
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.opener`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/opener
* Report started: 2021-02-17T03:34:28.563Z

</details>

**Comment by ddbeck** [comment] 2021-02-17 13:29
This issue appears to be empty. The issue is not different from the issue template and no actionable information has been provided.

If this has been closed in error, edit the title and body, and post a follow-up comment.

**Closed by ddbeck** 2021-02-17 13:29 UTC
Labels: invalid :no_entry_sign:
