### ISSUE TITLE
html.global_attributes.inputmode - Not Working Safari 14 in iOS

### ISSUE THREAD

**Issue by aeallord** [mdn/browser-compat-data#8940] opened 2021-02-03 03:25 UTC
Document indicated implemented in Safari 12.2 in iOS; tested in Safari on iOS 14.2 (Safari 14.x) and decimal pad is not shown.

I saw a number pad, expected a decimal pad

Tested on iPhone, iOS 14.2 using Safari. Number pad shows up only. Using inputmode did not bring up a decimal number pad as is desired in this field being developed. 

<details>
<summary>MDN page report details</summary>

* Query: `html.global_attributes.inputmode`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode
* Report started: 2021-02-03T03:20:23.968Z

</details>

**Comment by ddbeck** [comment] 2021-02-09 15:28
Thanks for reporting this, @aeallord.

Unfortunately, I was unable to reproduce the problem you found. For example, with the following code, I got two different keyboards—one with a dot key and one without—in the latest iOS Safari on BrowserStack:

```html
<div>
  <h2>numeric</h2>
  <input inputmode="numeric" />
</div>

<div>
  <h2>decimal</h2>
  <input inputmode="decimal" />
</div>
```

Since I was unable to reproduce this problem, I think the data we have is accurate (at least for recent versions of iOS) and I'm going to close this issue.

That said, investigating even suspected errors in the data helps us make sure that quality is high and improving. Thank you again for reporting this!

**Closed by ddbeck** 2021-02-09 15:28 UTC
Labels: data:html :page_facing_up:
