### ISSUE TITLE
api.HTMLCanvasElement.toBlob - Safari supports "quality" parameter for jpeg "type"

### ISSUE THREAD

**Issue by kirillshatalkin** [mdn/browser-compat-data#21408] opened 2023-12-01 13:23 UTC
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Safari supports "quality" parameter for jpeg "type"

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Version when Safari started to support it

### Did you test this? If so, how?

Tested on Safari 16.4 on MacOS 13.6 and Safari on iOS 17.1

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLCanvasElement.toBlob`
* Report started: 2023-12-01T13:15:15.889Z

</details>

**Comment by queengooborg** [comment] 2023-12-02 03:50
Would you mind providing your test code so that we may verify the accuracy of this report and track down the exact version number the feature was added in?

**Comment by queengooborg** [comment] 2023-12-02 06:07
Ah, actually, I see this is a duplicate of #21196.

**Closed by queengooborg** 2023-12-02 06:07 UTC
Labels: data:api :rabbit2:, info needed :mag:
