### ISSUE TITLE
Merge WebKitCSSMatrix into DOMMatrix

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#8054] opened 2020-12-19 12:08 UTC
We currently have both WebKitCSSMatrix.json and DOMMatrix.json. We should probably handle this with `prefix` entries in DOMMatrix.json instead.

@vinyldarkscratch this came to mind after merging https://github.com/mdn/browser-compat-data/pull/8044.

**Comment by ddbeck** [comment] 2021-01-14 12:19
This is a duplicate of #6726, which was mostly addressed in #6920. `WebKitCSSMatrix` is something of a special case. It's not an incidental prefix; it's [actually part of the spec for `DOMMatrix`](https://github.com/mdn/browser-compat-data/pull/5405#issue-356990845). I think we're stuck with it.

**Closed by ddbeck** 2021-01-14 12:19 UTC
Labels: data:api :rabbit2:
