### ISSUE TITLE
api.Element.scrollIntoView - Safari now supports options

### ISSUE THREAD

**Issue by jaredcwhite** [mdn/browser-compat-data#15982] opened 2022-04-23 03:19 UTC
#### What information was incorrect, unhelpful, or incomplete?

It says Safari doesn't support scrollIntoView options, but it's supported now in Safari. I'm not sure exactly which version added support, but it was fairly recent. Relevant information:

https://bugs.webkit.org/show_bug.cgi?id=188043

#### What did you expect to see?

Listing the version of Safari which added support for scrollIntoView options.

#### Did you test this? If so, how?

calling `el.scrollIntoVew({block: "center"})` will scroll the element into the middle of the page.

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.scrollIntoView`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView
* Report started: 2022-04-23T03:09:38.554Z

</details>

**Comment by queengooborg** [comment] 2022-06-16 00:29
Duplicate of #9055.

**Closed by queengooborg** 2022-06-16 00:29 UTC
Labels: duplicate :dancing_women:, data:api :rabbit2:
