### ISSUE TITLE
api.MediaMetadata - MediaMetadata is not a constructor

### ISSUE THREAD

**Issue by nidhi-canopas** [mdn/browser-compat-data#10833] opened 2021-06-07 12:13 UTC
Chrome : "57", platform : "electron.js"

#### What information was incorrect, unhelpful, or incomplete?
`Uncaught TypeError: MediaMetadata is not a constructor`

#### What did you expect to see?
Set custom info of playing sound without throwing error.
#### Did you test this? If so, how?
I've tested browser support with following code : 
```
if ('mediaSession' in navigator) {
 console.log("supports");
} else {
console.log("not supported");
}
```

actual code : 
```
if ("mediaSession" in navigator){
   let track = store.getters.coversPlayerCurrentTrack
  navigator.mediaSession.metadata =  new MediaMetadata({
  title: track.name,
  artist: track.artist,
  album: track.album,
  artwork: track.image_url
  });
}
```
#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?
It's working fiddle [https://codepen.io/idorenyinudoh/pen/vYKQVqQ](url)

**Comment by vinyldarkscratch** [comment] 2021-06-07 14:36
Looks like this is a duplicate of your other issue, #10819.

**Closed by vinyldarkscratch** 2021-06-07 14:36 UTC
