### ISSUE TITLE
api.structuredClone - Deno & Node are in the wrong place

### ISSUE THREAD

**Issue by theLMGN** [mdn/browser-compat-data#16362] opened 2022-05-19 10:25 UTC
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

The Deno & NodeJS entries are inserted in the "Desktop" and "Mobile" catgories, pushing Samsung Internet & WebView Android into the "Server" category.
![Uploading image.png…]()

### What browsers does this problem apply to, if applicable?

Node.js, Deno

### What did you expect to see?

Deno & Nodejs are in the correct place.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/structuredClone

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.structuredClone`
* Report started: 2022-05-19T10:22:49.022Z

</details>

**Comment by theLMGN** [comment] 2022-05-19 10:26
Note, this isn't specific to the structuredClone page. It occurs on other pages (such as https://developer.mozilla.org/en-US/docs/Web/API/Location, https://developer.mozilla.org/en-US/docs/Web/API/Console/log )

**Comment by teoli2003** [comment] 2022-05-19 10:50
Hi! 

Thank you!

This is a duplicate of mdn/yari#6314 which should be fixed very soon. I'm closing this issue.

**Closed by teoli2003** 2022-05-19 10:50 UTC
Labels: needs triage 🔎
