### ISSUE TITLE
javascript.builtins.Error.cause - Chrome doesn't display cause when logging error to console

### ISSUE THREAD

**Issue by NogrTL** [mdn/browser-compat-data#19004] opened 2023-02-24 15:03 UTC
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Chrome's behavior differs from Firefox.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Expected to see error stack from `cause ` when logging the error

### Did you test this? If so, how?

Run in Firefox and Edge

```js
function someDangerousLogic() {
  throw new Error("Whoops!");
}

function main() {
  try {
    someDangerousLogic();
  } catch (originalError) {
    throw new Error("Some additional, useful information", {
      cause: originalError,
    });
  }
}

main();
debugger;
```

[source](https://stackoverflow.com/a/73545352)

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Chromium issues - https://bugs.chromium.org/p/chromium/issues/detail?id=1211260

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Error.cause`
* Report started: 2023-02-24T14:59:20.550Z

</details>

**Comment by Josh-Cena** [comment] 2023-03-28 06:05
I don't think this counts as a partial implementation. Stack is not part of the spec, so Chrome isn't doing anything "partial" relative to the spec—it is fully compliant.

**Comment by NogrTL** [comment] 2023-03-28 07:53
> I don't think this counts as a partial implementation. Stack is not part of the spec, so Chrome isn't doing anything "partial" relative to the spec—it is fully compliant.

Maybe it's a part of some other spec, like `console.error`?

**Comment by Josh-Cena** [comment] 2023-03-28 14:14
None that I'm aware of—error information is entirely implementation-defined. For example, https://console.spec.whatwg.org/#printer leaves the entire printer to the implementation.

I agree that a note would be helpful since message context is most of the reason why `cause` exists at all, but I'm not sure if you can add notes without marking it as partial.

**Comment by NogrTL** [comment] 2023-03-29 07:37
> None that I'm aware of—error information is entirely implementation-defined. For example, https://console.spec.whatwg.org/#printer leaves the entire printer to the implementation.
> 
> I agree that a note would be helpful since message context is most of the reason why `cause` exists at all, but I'm not sure if you can add notes without marking it as partial.

Agree, a note would be nice. Because it looks like cause doesn't do anything at all in Chromium.

**Comment by queengooborg** [comment] 2023-12-10 18:19
In my testing, neither Chrome or Safari display the cause:

<img width="2056" alt="image" src="https://github.com/mdn/browser-compat-data/assets/5179191/7a29f9a2-5abf-4387-9153-2cc12039fb76">

While this isn't a spec-defined feature (so it DEFINITELY doesn't count for partial implementation), I've submitted a PR to add a subfeature in BCD to track this.

**Closed** 2023-12-12 12:18 UTC
Labels: data:js :pager:
