### ISSUE TITLE
api.GPU - Chrome has wide support for WebGPU

### ISSUE THREAD

**Issue by quinton-ashley** [mdn/browser-compat-data#25436] opened 2024-12-16 21:21 UTC
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Chrome is marked as having limited support, perhaps by mistake because Edge is marked as having a green check for WebGPU support in the browser baseline banner.

### What did you expect to see?

Chrome with a green check

### Did you test this? If so, how?

Yes, webgpu can run in Chrome

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebGPU_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.GPU`
* Report started: 2024-12-16T21:17:38.074Z

</details>

**Comment by caugner** [comment] 2024-12-18 09:58
Thanks for reporting! 🙌 

This is an issue with the Baseline banner on MDN, not a BCD data issue, and will be fixed once https://github.com/mdn/yari/issues/11546#issuecomment-2531611136 is implemented.

Closing this as a duplicate of https://github.com/mdn/yari/issues/12297.

**Closed by caugner** 2024-12-18 09:58 UTC
Labels: data:api
