### ISSUE TITLE
http.headers.Sec-CH-UA-Platform - Samsung browser 20.0 is not sending client hints headers

### ISSUE THREAD

**Issue by moverstrom-comscore** [mdn/browser-compat-data#19604] opened 2023-05-01 20:18 UTC
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

MDN docs state that the Samsung browser supports user agent client hints such as Sec-CH-UA-Platform, but these are not provided as of Samsung Browser version 20, based on my testing.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

I expected the browser to provide the Sec-CH-UA-Platform header in requests after it is requested by the server.

### Did you test this? If so, how?

Used the test at: https://user-agent-client-hints.glitch.me/headers?uach=Sec-CH-UA-Arch&uach=Sec-CH-UA-Bitness&uach=Sec-CH-UA-Full-Version&uach=Sec-CH-UA-Full-Version-List&uach=Sec-CH-UA-Mobile&uach=Sec-CH-UA-Model&uach=Sec-CH-UA-Platform-Version&uach=Sec-CH-UA-Platform&uach=Sec-CH-UA-Wow64&uach=Sec-CH-UA

This was on a Google Pixel 3 running Android 12.

![image](https://user-images.githubusercontent.com/47902968/235523435-321c0394-f027-4d8a-8859-75725fa91a8a.png)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-UA-Platform

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Sec-CH-UA-Platform`
* Report started: 2023-05-01T18:29:25.740Z

</details>

**Comment by queengooborg** [comment] 2023-12-06 03:26
Duplicate of #15821.

**Closed by queengooborg** 2023-12-06 03:26 UTC
Labels: data:http :mountain_cableway:, needs triage 🔎
