### ISSUE TITLE
IE fail to set Content-Type header on XHR whose body is a typed Blob

### ISSUE THREAD

**Issue by jimmywarting** [mdn/browser-compat-data#2596] opened 2018-08-13 21:51 UTC
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/6047383/

Would be good to know when sending blobs 👍 if you can flag that

**Comment by vinyldarkscratch** [comment] 2019-04-16 08:42
From what it looks like on the linked issue page, it's been marked as "not reproducible" since Jul 7, 2017.  Happy to have a note about this, but I'd like to get confirmation that this is actually an issue beforehand.  Are you able to reproduce this?

**Comment by jimmywarting** [comment] 2019-04-16 09:12
```js
xhr = new XMLHttpRequest()

xhr.open('POST', 'https://httpbin.org/post')
xhr.responseType = 'json'
xhr.onload = function() {
  console.log(xhr.response.headers['Content-Type'] === 'text/plain')
}
xhr.send(new Blob(['abc'], {type: 'text/plain'}))
```

**Comment by vinyldarkscratch** [comment] 2019-04-16 09:41
Running this test logged `true` in the console.  Changing the type in the Blob constructor to random strings (`text/json`, `application/exe`) still returned `true`.  Did you have a different result?

**Comment by jimmywarting** [comment] 2019-04-16 10:22
Test it in a old ie browser

**Comment by vinyldarkscratch** [comment] 2019-04-16 10:28
Ah, so this is an issue affecting older versions of IE, that explains it!  Thanks for the additional information.  This is definitely something to dig further into, as to figure out which particular version this was fixed in.

**Comment by vinyldarkscratch** [comment] 2019-06-27 07:46
Took me a while to get to this (took a little break from BCD to work on personal projects).  I was still unable to reproduce the issue.  IE 10 was the first version to implement `Blob`, and it also returns `true`.

I'm going to go ahead and close this issue.

**Closed by vinyldarkscratch** 2019-06-27 07:46 UTC
Labels: data:api :rabbit2:
