### ISSUE TITLE
Lint for broken HTML

### ISSUE THREAD

**Issue by wbamberg** [mdn/browser-compat-data#3985] opened 2019-04-24 21:32 UTC
As far as I can tell, this: https://github.com/mdn/browser-compat-data/pull/3978 could have been caught by a linter checking for valid HTML (using e.g. https://validator.w3.org/).

**Comment by queengooborg** [comment] 2022-04-10 06:45
Closing as a duplicate of #2799 (I realize it's been a long time since this issue was opened).

**Closed by queengooborg** 2022-04-10 06:45 UTC
Labels: linter :house_with_garden:
