### ISSUE TITLE
css.properties.clip-path - <geometry-box> not supported by Chromium

### ISSUE THREAD

**Issue by dakshdua** [mdn/browser-compat-data#19165] opened 2023-03-17 19:53 UTC
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

The table mentions that `fill-box` and `stroke-box` are not supported outside of Firefox, but it seems that `<geometry-box>` in general is not supported in Chromium. The table gave me the impression that only `fill-box` and `stroke-box` were not supported but other values of the `<geometry-box>` type would be supported.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

I expected to see a row for the `<geometry-box>` type's support instead of just `fill-box` and `stroke-box`.

### Did you test this? If so, how?

I attempted to use all `<geometry-box>` types in a clip path property in Chrome and none were valid.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Chromium issue for `<geometry-box>` support: https://bugs.chromium.org/p/chromium/issues/detail?id=694218

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.clip-path`
* Report started: 2023-03-17T19:46:06.784Z

</details>

**Comment by queengooborg** [comment] 2023-12-10 18:51
Duplicate of #15962.

**Closed by queengooborg** 2023-12-10 18:51 UTC
Labels: data:css :art:
