### ISSUE TITLE
Issue with "DataTransfer.setDragImage()": (chrome 99 )

### ISSUE THREAD

**Issue by Yuandiaodiaodiao** [mdn/browser-compat-data#15435] opened 2022-03-18 13:27 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/setDragImage

#### What information was incorrect, unhelpful, or incomplete?

in chrome 99
you need deal xOffset with devicePixelRatio
but in chrome 96 not need

img.style.width = '100px'
  img.style.height = '100px'
dataTransfer.setDragImage(img,100, 100);

those code show difference behavier between chrome 96 and chrome99
#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/datatransfer/setdragimage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/setDragImage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/datatransfer/setdragimage/index.md
* Last commit: https://github.com/mdn/content/commit/89c8199b06e7fb2b76da4087cb9eedef065b2506
* Document last modified: 2022-02-18T09:24:31.000Z

</details>

**Comment by lukewarlow** [comment] 2022-03-30 21:33
This sounds like it would be better directed at the Chrome bug tracker. If you do file a bug feel free to put the link down on this issue and someone can add it to the notes field in the data if it seems necessary.

**Comment by queengooborg** [comment] 2023-08-06 19:57
I'm going to close this because there's not enough information to be able to determine what the issue is, and as mentioned above, filing a bug with Chrome would be better anyways.

**Closed by queengooborg** 2023-08-06 19:57 UTC
Labels: data:api :rabbit2:
