### ISSUE TITLE
StorageAccessApi -  Issue only with firefox on Ios devices only

### ISSUE THREAD

**Issue by ygag-kishore** [mdn/browser-compat-data#18497] opened 2022-12-29 11:14 UTC
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

Hi Everyone,

I have implemented storage access API on safari since safari blocks third party cookies by default. So we did a workaround like the user has to make interactions on both third party and first party page. Our webpage is iframed with another one we need to store some cookies in the session partition. So we came up like the user will land to our page first (page inside iframe) next we will redirect him to the next page(first party page) then upon click a button he will be back to previous page(iframe). This storage access api workaround implementation works well on safari and chrome but not on firefox ios devices only. The browser shows "Your browser doesnt support some of the feeatures on this site. Better upgrade your browser or switch to another browser". But my browser is up to date with the latest version. (108.1)

In mdn docs also there is no explicit mention of this storageaccessapi support for ios devices from firefox it has mentioned only for android if they arent supported for ios atleast mention the same on docs. Please advise on this issue and also mention the workaround if anybody has idea

### What did you expect to see?

I expected to see my homepage. But its showing "Your browser doesn't support some features on this site. Update your browser or switch to a new browser"

### Did you test this? If so, how?

Yes, I downloaded the ltatest version of firefox from app store on ios device and tried loading my website which resides inside an iframe then the firefox showed the above message

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Actually the version is 108.1. Since it is related to my work I can't share any screenshots. Any help on this would be greatly appreciated

### Do you have anything more you want to share?

as of now code i cannot share as it is violating my company policy

**Comment by queengooborg** [comment] 2022-12-29 16:35
Hi @ygag-kishore, this is a duplicate of your other issue, #18490, which was closed as irrelevant to the project.  Once again, this is a _development_ problem, and BCD _cannot provide development help_.  We would recommend asking on a site like StackOverflow, but if you are unable to provide code examples, I'm afraid you won't get too far anyways.

Please do not open another issue regarding the same problem or reopen either of your existing two.  This will be considered spam and may result in exclusion from participating in MDN repositories.

(By the way, in regard to other iOS browsers, due to the nature of the operating system, all browsers are simply using Safari as their backend.  As such, even if you are using Chrome, Firefox or some other third-party browser, they are using Safari's engine which is built right into the OS.  The "Safari for iOS" column will give you an idea of what features are supported for each iOS and iPadOS version.)

**Closed by queengooborg** 2022-12-29 16:35 UTC
Labels: needs triage 🔎
