### ISSUE TITLE
navigator.share is not a function Error on Chrome Android

### ISSUE THREAD

**Issue by fmabid** [mdn/browser-compat-data#10736] opened 2021-06-03 06:48 UTC
I don't know if the `Supported Browser` section is updated or not about the Versions at [https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#browser_compatibility](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#browser_compatibility) I was testing this API on "Chrome Android". It'sgiving an Error saying **`navigator.share is not a function`**.

But it's working good on Safari.

**Comment by queengooborg** [comment] 2023-02-09 09:55
Thank you for reporting this issue, and so sorry that it took so long to get to it.

I'm confused by your message.  You're stating that you tested Chrome Android and found no support, but that it also works in Safari?  Are you referring to two separate devices?  If not, do you mean Chrome on iOS/iPadOS?

I can confirm that Chrome Android does have support for this feature, tested across multiple Android devices.  If you're testing on an iPhone or iPad, then you're not using Chrome Android.  Some third-party browsers don't have support for certain features, either because they disable it or due to embedded WebKit limitations.  We actually don't track other iOS/iPadOS browsers because their compatibility is so similar.

I'm going to close this issue as we don't have enough actionable information to make any corrections to the data (and considering it's been two years, I'm not expecting to receive a reply).  But please feel free to reply to this thread any time and share additional details regarding your test environment, device, whether you're using HTTP vs. HTTPS, etc.!

**Closed by queengooborg** 2023-02-09 09:55 UTC
Labels: data:api :rabbit2:
