### ISSUE TITLE
css.types.url - missing images on Google Chrome on Android

### ISSUE THREAD

**Issue by mliebelt** [mdn/browser-compat-data#9037] opened 2021-02-08 17:54 UTC
I want to fix the bug https://github.com/mliebelt/PgnViewerJS/issues/180 of my library, which works on all browsers. The only one not working at the moment is Chrome on Android 
 Chrome 88.0.4324.152, Android 10; ONeplus A6013

For some strange reason, the display is correct on Google Chrome on Android in the incognito version.

#### What information was incorrect, unhelpful, or incomplete?

When calling the examples on the example website, https://mliebelt.github.io/PgnViewerJS/examples.html#1000, the figures on all board are missing. The figures are denoted by a relative URL, that is then transferred by WebPack to some assets directory. In the source, the url is used relative, see the [source file for it](https://github.com/mliebelt/PgnViewerJS/blob/master/modules/pgn-viewer/src/css/theme.css). The pieces from line 35 and below are not displayed.

#### What did you expect to see?

All pieces should be shown as in all other brothers.

#### Did you test this? If so, how?

The test is to open the website, and click through the examples: https://mliebelt.github.io/PgnViewerJS/examples.html#1000

<details>
<summary>MDN page report details</summary>

* Query: `css.types.url`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/url()
* Report started: 2021-02-08T17:36:21.486Z

</details>

**Comment by ddbeck** [comment] 2021-02-09 18:27
Hi @mliebelt. Thanks for reporting this. Unfortunately, I wasn't able to reproduce the problem with `url()` you reported (neither in your link nor in independent testing of `url()`). Since I am unable to reproduce this, I am going to close this issue.

That said, if you find that this is a bug in Chrome (that for whatever reason, is difficult to duplicate on all devices) and merits a mention in our browser compatibility data, then please feel free to follow up here with a link to a relevant Chromium bug or similar citation we could use in a note.

Thank you!

**Closed by ddbeck** 2021-02-09 18:27 UTC
Labels: data:css :art:

**Comment by mliebelt** [comment] 2021-02-10 06:59
Thank you @ddbeck  for investing your time. I understand closing that issue, if it is so difficult to reproduce.

Here are some more details to the above issue:

* I have a reported bug by a user: https://github.com/mliebelt/PgnViewerJS/issues/180
* That user was able to go into deeper analysis and found, that URLs like
  * `url(https://mliebelt.github.io/PgnViewerJS/js/pgnv-assets/46c4b3a….svg);` are working.
  * `url(/PgnViewerJS/js/pgnv-assets/e1a52ad….svg);` is *not* working.
  * `url(js/pgnv-assets/e1a52ad….svg);` is working.

So it seems to be related the kind of transformation that is done by the tools that build the resulting javascript file, and its replacements done on the original CSS file. I will try to bundle the assets in a different way, to see if that solves my problem as well.

----

Having read the ticket, I tried doing USB debugging myself. I had strange effects in doing that:

* While doing USB debugging, working in the remote Chrome browser, suddenly all images where displayed. This was stable then during that USB debugging session (see pgnv1). It broke again when I closed the debugging session, and load the tabs in the browser anew.
* Repeating it, I had the empty board again, and could selectively go to each piece, edit its URL (switching first to url(js/pgnv-assets/e1a52ad….svg) format, then back to url(/PgnViewerJS/js/pgnv-assets/e1a52ad….svg) ), and had it visible then all the time (see pgnv2).

![pgnv1](https://user-images.githubusercontent.com/520039/107476134-8f08db00-6b75-11eb-93ac-29e7f1bf1de3.jpg)
![pgnv2](https://user-images.githubusercontent.com/520039/107476143-93cd8f00-6b75-11eb-8fc1-311dd98e6fde.jpg)

**Comment by ddbeck** [comment] 2021-02-10 09:44
> So it seems to be related the kind of transformation that is done by the tools that build the resulting javascript file, and its replacements done on the original CSS file.

This seems likely. Unfortunately, this sort of thing is out of scope for BCD. We track support for the features that browsers directly implement, not intermediate tooling. When it comes to this project, we would need a very reduced test case (ideally, a few lines of HTML and CSS alone) to demonstrate an issue and record it in our data set. 

Good luck solving your bug, one way or another!
