### ISSUE TITLE
Web App Manifests lack data for the feature as a whole.

### ISSUE THREAD

**Issue by jpmedley** [mdn/browser-compat-data#16687] opened 2022-06-15 21:21 UTC
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

The [data for Web App Manifests](https://github.com/mdn/browser-compat-data/tree/main/html/manifest) contains entries for individual members, but no entry for the feature as a whole. Consequently, the top line of the [MDN browser compat table](https://developer.mozilla.org/en-US/docs/Web/Manifest#browser_compatibility) does not give a general impression of the feature's support as is typical of most platform features. (There's also no data to pull into a [macros used on a Goolge site](https://web.dev/handbook/web-dev-components/#browsercompat) that shows support for a feature.)

### What did you expect to see?

A file that covers manifests over all.

**Comment by queengooborg** [comment] 2023-08-09 02:59
Although it's newer, I'm going to close this as a duplicate of #18493 (it has more information and discussion).

**Closed by queengooborg** 2023-08-09 02:59 UTC
Labels: data:html :page_facing_up:, needs triage 🔎
