### ISSUE TITLE
webextensions.api.tabs.captureVisibleTab - <Firefox Authenticator>

### ISSUE THREAD

**Issue by JanGray** [mdn/browser-compat-data#13672] opened 2021-11-22 02:09 UTC
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.api.tabs.captureVisibleTab`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/captureVisibleTab
* Report started: 2021-11-22T02:05:45.667Z

</Could not sign in>

**Comment by queengooborg** [comment] 2021-11-22 08:52
This issue was closed because it appears to be empty. The issue is not different from the issue template and no actionable information has been provided.

If this has been closed in error, edit the title and body, and post a follow-up comment.

**Closed by queengooborg** 2021-11-22 08:52 UTC
