### ISSUE TITLE
Not able to use keyboard in Mobile to enter date manually

### ISSUE THREAD

**Issue by manoj7594** [mdn/browser-compat-data#18836] opened 2023-02-07 10:33 UTC
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

Not able to use keyboard in Mobile to enter date manually

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Enter DOB manually in mobile

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.input.type_date`
* Report started: 2023-02-07T10:29:44.553Z

</details>

**Comment by queengooborg** [comment] 2023-02-08 04:10
There's not enough details provided to be able to determine what the issue is, so closing.

**Closed** 2023-02-08 04:10 UTC
Labels: spam :wastebasket:
