### ISSUE TITLE
css.properties.clip-path - <geometry-box> row doesn't reflect unavailability for HTML in WebKit

### ISSUE THREAD

**Issue by landisdesign** [mdn/browser-compat-data#20149] opened 2023-06-16 15:52 UTC
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

While the svg `fill-box` and `stroke-box` options are identified, there's nothing referencing that `content-box`/`padding-box`/`border-box`/`margin-box` don't work on HTML elements on the Mac, presumably because they all use WebKit.

### What browsers does this problem apply to, if applicable?

Firefox, Safari

### What did you expect to see?

An additional row reflecting HTML-specific compatibility

### Did you test this? If so, how?

Applying `clip-path: padding-box` to a test element with border radius. Its children show through plainly.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

The examples provided in the page indicate WebKit's failure to implement this feature:

https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path#comparison_of_html_and_svg

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.clip-path`
* Report started: 2023-06-16T15:18:16.417Z

</details>

**Comment by queengooborg** [comment] 2023-12-10 19:35
Duplicate of #15962.

**Closed by queengooborg** 2023-12-10 19:35 UTC
Labels: data:css :art:
