### ISSUE TITLE
api.RTCDataChannel.binaryType - <Blob support not implemented yet>

### ISSUE THREAD

**Issue by FickXu** [mdn/browser-compat-data#14034] opened 2021-12-16 05:57 UTC
#### What information was incorrect, unhelpful, or incomplete?
浏览器兼容性信息不准确
_Translation: Browser compatibility information is inaccurate_
#### What did you expect to see?
建议修改文档使文档更准确
_Translation: It is recommended to modify the document to make the document more accurate_
#### Did you test this? If so, how?
我在Chrome(version:96.0.4664.110),Opera(version:82.0.4227.23),Edge(version:96.0.1054.53),Firefox(version:95.0)上测试了binaryType属性，只有Firefox支持。代码如下：

_Translation: I tested the `binaryType` property on Chrome (version: 96.0.4664.110), Opera (version: 82.0.4227.23), Edge (version: 96.0.1054.53), and Firefox (version: 95.0), and only Firefox supports it. I used the following code:_

```js
...
localConnection = new RTCPeerConnection();
sendChannel = localConnection.createDataChannel("sendChannel");
sendChannel.binaryType = "blob";
...
sendChannel.send(file)
```

Chrome，Opera，Edge报错 [report errors]：DOMException: Failed to execute 'send' on 'RTCDataChannel': Blob support not implemented yet
    at...

<details>
<summary>MDN page report details</summary>

* Query: `api.RTCDataChannel.binaryType`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/binaryType
* Report started: 2021-12-16T01:56:42.246Z

</details>

**Comment by queengooborg** [comment] 2021-12-24 00:57
Duplicate of #6770.

**Closed by queengooborg** 2021-12-24 00:57 UTC
Labels: data:api :rabbit2:
