### ISSUE TITLE
html.elements.input.type_range - tick marks work in safari

### ISSUE THREAD

**Issue by jackbow** [mdn/browser-compat-data#18102] opened 2022-10-28 20:48 UTC
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range#browser_compatibility
Under "Tick mark support", Safari is listed as not supporting tick marks.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

It should be Yes with implementation notes, and the implementation note should be along the lines of "Tick marks appear above slider, and to the left in vertical orientation. Tick mark labels are not supported"

### Did you test this? If so, how?

I opened it in Safari. Here's a Safari screenshot of result section of https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range#adding_hash_marks
<img width="246" alt="Screenshot 2022-10-28 at 4 43 58 PM" src="https://user-images.githubusercontent.com/15710512/198729348-25f47e9f-4a8b-4a23-a4f1-26e728bdb525.png">
The next section's result with labels is visually identical.

### Do you have anything more you want to share?

I'm using Safari version 16.1 (18614.2.9.1.12)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.input.type_range`
* Report started: 2022-10-28T20:35:14.467Z

</details>

**Comment by jackbow** [comment] 2022-10-28 20:50
Seems like this has been an issue for awhile. https://github.com/mdn/browser-compat-data/issues/9867

**Comment by queengooborg** [comment] 2023-02-12 07:50
Closing as a duplicate of #9867.

**Closed by queengooborg** 2023-02-12 07:50 UTC
Labels: data:html :page_facing_up:, needs triage 🔎
