### ISSUE TITLE
http.status - no browser compatibility data for multiple HTTP status codes

### ISSUE THREAD

**Issue by kaduk** [mdn/browser-compat-data#12015] opened 2021-08-16 16:34 UTC
The linked page https://developer.mozilla.org/en-US/docs/Web/HTTP/Status has a really convenient table indicating browser compatibility/support for various HTTP status codes.  However, there are a number of HTTP status codes with no corresponding row in the table, such as 101, 202, 203, 205, 300, 305, 400, 405, 408, 411, 413, 414, 415, 417, 421, 422, 426, and 505.  While some of these don't exactly make sense to provide generic support for, others (e.g., 421) are generically useful.  Having a more complete table would be helpful for HTTP server authors.

<details>
<summary>MDN page report details</summary>

* Query: `http.status`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
* Report started: 2021-08-16T16:25:36.476Z

</details>

**Comment by Elchi3** [comment] 2023-08-10 09:47
Duplicate of https://github.com/mdn/browser-compat-data/issues/8936

**Closed by Elchi3** 2023-08-10 09:47 UTC
Labels: data:http :mountain_cableway:
