### ISSUE TITLE
api.ServiceWorkerContainer.register - firefox don't support all options like type=module

### ISSUE THREAD

**Issue by Eccenux** [mdn/browser-compat-data#17023] opened 2022-07-17 12:33 UTC
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

It shows that Firefox supports everything which is misleading.
https://bugzilla.mozilla.org/show_bug.cgi?id=1812591

### What browsers does this problem apply to, if applicable?

Firefox 102.
Works in Chrome since version 91.

https://web.dev/articles/es-modules-in-sw#browser_support

### What did you expect to see?

Either split table to separate options support or at least add notes in "*" implementation notes. I guess for future would more useful to have separate options to know in which version modules will be supported.

### Did you test this? If so, how?

As an example this SW is not loading (works fine in Chrome):
https://jcubic.github.io/wayne/

```
if ('serviceWorker' in navigator) {
    const scope = location.pathname.replace(/\/[^\/]+$/, '/');
    navigator.serviceWorker.register('sw.js', {scope, type: 'module'})
             .then(function(reg) {
                 // this is never executed...
                 console.log('Registration succeeded...');
             }).catch(function(error) {
                 // registration failed
                 console.log('Registration failed with ' + error);
                 // result: Registration failed with TypeError: ServiceWorker script at https://jcubic.github.io/wayne/sw.js for scope https://jcubic.github.io/wayne/ threw an exception during script evaluation.
             });
}
```

sw.js looks something like this (except for that import part nothing should cause problems):
```
import { Wayne } from 'https://cdn.jsdelivr.net/gh/jcubic/wayne@master/index.js';

// nothing out of ordinary here...
```

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

I guess most importantly module support in SW is marked as an open feature:
https://bugzilla.mozilla.org/show_bug.cgi?id=1247687

Would be nice to have a link to this bug in notes or somewhere.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/register

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.ServiceWorkerContainer.register`
* Report started: 2022-07-17T12:07:17.445Z

</details>

**Comment by Eccenux** [comment] 2022-07-17 12:54
Safari/Webkit seems to have implemented this in 2021-03, but that was only in a preview version... Seems like this landed in final versions of Safari 15 for desktop and mobile. Haven't tested but there is mention about ES modules here:
https://developer.mozilla.org/en-US/docs/Web/API/Worker#browser_compatibility

**Comment by queengooborg** [comment] 2023-12-08 02:53
Duplicate of #15298.

**Comment by queengooborg** [comment] 2023-12-08 02:55
Actually, I'm going to reopen this and close the other one because this has more information.

**Comment by jimmywarting** [comment] 2023-12-08 10:08
Could be worth mentioning with a `*` that it will not support dynamic / lazy `import()`

**Comment by daniel-nagy** [comment] 2023-12-21 15:19
Does Firefox not support service worker scripts of type module? My tests are failing in Firefox and it seems to be because of module imports inside the service worker.

**Comment by dmchurch** [comment] 2023-12-23 20:25
> Does Firefox not support service worker scripts of type module? My tests are failing in Firefox and it seems to be because of module imports inside the service worker.

That's the conclusion that I've finally come to as well after a couple days of testing and scratching my head, and caniuse agrees:

https://caniuse.com/mdn-api_serviceworker_ecmascript_modules
![image](https://github.com/mdn/browser-compat-data/assets/605817/72c44714-a7ab-4f67-838a-6c4afcf618f4)

Can we PLEASE get this MDN page updated? It's been over a year, and this continues to be inaccurate and it continues to waste peoples' time!

**Comment by queengooborg** [comment] 2023-12-28 06:31
FYI, we do have information for whether ES modules are supported as service workers -- see https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker#browser_compatibility.  It is outdated, so I've submitted a PR to fix it up, see https://github.com/mdn/browser-compat-data/pull/21767.

I've also opened a pull request to add a link to the corresponding BCD table on MDN, see https://github.com/mdn/content/pull/31361#pullrequestreview-1797715428.

---

> and caniuse agrees

@dmchurch, that data actually comes from here!  CanIUse includes BCD in its search results, and you can tell when the results are from BCD by the URL (the page slug will be prefixed with `mdn-`) and by the copyright notice ("Support data for this feature provided by: MDN browser-compat-data") underneath the table.  😛

**Closed** 2024-01-07 23:32 UTC
Labels: data:api :rabbit2:
