### ISSUE TITLE
All features - Internet Explorer compatibility data missing

### ISSUE THREAD

**Issue by caseyjhol** [mdn/browser-compat-data#17531] opened 2022-08-23 17:44 UTC
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Data for Internet Explorer is missing from the compatibility table for every feature. It's included in the source, but not displaying in the table.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf#browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#browser_compatibility

### Do you have anything more you want to share?

![image](https://user-images.githubusercontent.com/2874325/186228407-f1b2724b-3765-4ed7-a536-4cc8b8f951a7.png)

**Comment by queengooborg** [comment] 2022-08-23 17:56
Duplicate of https://github.com/mdn/yari/issues/6932.

**Closed by queengooborg** 2022-08-23 17:56 UTC
Labels: needs triage 🔎
