### ISSUE TITLE
html.elements.input.input-date - Not working in safari 

### ISSUE THREAD

**Issue by pankajvashisht-ucreate** [mdn/browser-compat-data#10419] opened 2021-05-10 11:35 UTC
#### What information was incorrect, unhelpful, or incomplete?
I have noticed input type date and time is not working in the safari borwer. Maybe it's working in the older version but it's not working in my mac. 

#### What did you expect to see?

If it's supported then it should be work.

#### Did you test this? If so, how?
I have tested this in multiple mac safari but it's not working. I have implemented this in many projects but in the safari browser, it's showing the text field. Even on your website, it's not working.

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.input.input-date`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date
* Report started: 2021-05-10T11:22:30.774Z

</details>

**Comment by queengooborg** [comment] 2021-12-24 22:09
I'm unable to confirm a lack of support in Safari Desktop, nor Safari iOS.  I'm using Safari 15.1, and it looks like this functionality was just added in v14.1 as indicated by #10129 (which I've confirmed in BrowserStack).

I'm going to close this issue under the assumption that all is good, but if you're still having troubles, please don't hesitate to respond to this thread and I'll happily reopen the issue!

**Closed by queengooborg** 2021-12-24 22:09 UTC
Labels: data:html :page_facing_up:
