### ISSUE TITLE
html.elements.link.rel.manifest - browser support exists, BCD claims otherwise

### ISSUE THREAD

**Issue by estelle** [mdn/browser-compat-data#19891] opened 2023-05-18 21:27 UTC
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The BCD makes it look like the `manifest` rel value is not supported, but it is. For example, the `name` key is supported as per https://developer.mozilla.org/en-US/docs/Web/Manifest/name#browser_compatibility, but https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel and https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link indicate otherwise

### What did you expect to see?

the rel.manifest is confusing. does it mean rel="manifest"?

### Did you test this? If so, how?

i saw that i could install pwas and the shortname came from the manifest file

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/manifest

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.link.rel.manifest`
* Report started: 2023-05-18T21:21:21.147Z

</details>

**Comment by queengooborg** [comment] 2023-12-10 19:30
Duplicate of #19187.

**Closed by queengooborg** 2023-12-10 19:30 UTC
Labels: data:html :page_facing_up:
