### ISSUE TITLE
Consider using the browser version, instead of the OS version, for iOS Safari

### ISSUE THREAD

**Issue by othermaciej** [mdn/browser-compat-data#6338] opened 2020-06-26 02:28 UTC
The browser compat data seems to use the OS version number as the iOS Safari version. This is not the same as for any other desktop or mobile browser, where the browser version is used instead.

This also has the potential to confuse, because the same number can be used at different times as the OS version and the browser version. The Safari browser version does not align with the OS, it aligns with Safari for other platforms. For example, iOS 13 shipped with Safari 13, but iOS 13.4 shipped with Safari 13.1.

If this is not changed, at least the column header or entries should make clear that this is the OS version, not the browser version. Both are present in the Safari User-Agent string.

For example, here's the UA string for Safari on iOS 13.4.1. Note Version/13.1. That's the browser version.

`Mozilla/5.0 (iPhone; CPU iPhone OS 13_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Mobile/15E148 Safari/604.1`

**Comment by vinyldarkscratch** [comment] 2020-06-26 03:19
We use the iOS and iPadOS version for Safari for iOS/iPadOS per direct request of Apple; see https://github.com/mdn/browser-compat-data/issues/2006#issuecomment-457277312.  Seeing as this discussion has come up a few times, however, something to help clarify on the MDN web docs would probably be helpful -- we're certainly open to suggestions!

Issues for the layout and UI on MDN web docs are in the `kuma` repository, if you'd like to open an issue there: https://github.com/mdn/kuma/issues/new?assignees=&labels=status%3A+needs+triage&template=change-request.md&title=

(This is a duplicate of #5776, so I'm going to close this.)

**Comment by othermaciej** [comment] 2020-06-26 04:30
I'm syncing up with @apple-web-evangelist offline.

**Comment by vinyldarkscratch** [comment] 2020-06-26 05:11
I am now just realizing that you work at Apple, specifically on WebKit -- oops, my bad!  😅

I'll go ahead and reopen this issue then.  Yeah, let us know what you would like us to do going forward!

**Comment by othermaciej** [comment] 2020-06-26 06:52
Well, to be fair, I didn't say it in my original issue. We're going to sync internally on the best way to represent iOS Safari issues.

**Closed** 2023-08-10 09:02 UTC
Labels: data:browsers :earth_africa:, idle 🐌
