### ISSUE TITLE
Switch master to main?

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#7359] opened 2020-11-14 17:12 UTC
I know larger repositories tend to just keep using master, but I still had to raise this. Could we do this? PRs can easily switch their base branches via web, so I don't think it's a serious blocker.

**Comment by vinyldarkscratch** [comment] 2020-11-16 02:59
Duplicate of #6292.

**Closed by vinyldarkscratch** 2020-11-16 02:59 UTC
