### ISSUE TITLE
html.elements.input.type_datetime-local - Time picker not shown

### ISSUE THREAD

**Issue by pizzi80** [mdn/browser-compat-data#21103] opened 2023-10-27 08:45 UTC
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

Firefox in not compatible with  

`input type="datetime-local"`

My User Agent is 

Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

A calendar plus a time of the day chooser like in other browsers, for example in Chrome 
it's implemented in this way:

![Schermata del 2023-10-27 10-39-37](https://github.com/mdn/browser-compat-data/assets/17908214/68ae94a1-fc33-4207-ba73-60fca07e2403)

### Did you test this? If so, how?

Yes, many times, from 3 or 4 years now... 

**TO REPRODUCE**

Go to: https://developer.mozilla.org/en-US/play

Paste the following html code:

```
<form>
  <label for="party">Enter a date and time for your party booking:</label>
  <input id="party" type="datetime-local" name="partydate" />
</form>
```

and you will see that is not possible to choose date and time for the input
because there is not Time Chooser!

![Schermata del 2023-10-27 10-29-25](https://github.com/mdn/browser-compat-data/assets/17908214/0e4c8fda-1da0-4a9a-bd2f-280136b4650d)

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://bugzilla.mozilla.org/show_bug.cgi?id=1726108

### Do you have anything more you want to share?

A lot of devs and users are waiting from many years that Firefox fill this gap with other browsers!

Due to this bug Firefox is still not usable as a main browser
... people will continue to use Chrome, Safari or Edge instead of switching to Firefox ...

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.input.type_datetime-local`
* Report started: 2023-10-27T08:25:55.813Z

</details>

**Comment by lukewarlow** [comment] 2023-11-01 22:05
This imo isn't a compat data issue, Mozilla has just chosen not to make a picker UI for the time aspect (neither have Apple in Safari). They both fully recognise the input type and provide UI to edit the full value (just typing in the input itself).

**Comment by queengooborg** [comment] 2023-12-06 04:07
Duplicate of #16138.

**Closed by queengooborg** 2023-12-06 04:07 UTC
Labels: data:html :page_facing_up:, needs triage 🔎
