### ISSUE TITLE
html.elements.link.rel.preload - Browser compatibility safari

### ISSUE THREAD

**Issue by wanglemicrosoft** [mdn/browser-compat-data#19025] opened 2023-02-27 23:22 UTC
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Udpate Safari on iOS with Compatibility unknown (question mark), it's working on iOS version 16.3.1.
MacOS safari version 16.1 is working as well.

### What did you expect to see?

Same as above

### Did you test this? If so, how?

Yes.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/preload

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.link.rel.preload`
* Report started: 2023-02-27T23:14:31.904Z

</details>

**Comment by queengooborg** [comment] 2023-08-09 17:45
Duplicate of #15263.

**Closed by queengooborg** 2023-08-09 17:45 UTC
Labels: duplicate :dancing_women:, data:html :page_facing_up:
