### ISSUE TITLE
css.properties.clip-path - Missing support information for `path`

### ISSUE THREAD

**Issue by schalkneethling** [mdn/browser-compat-data#8765] opened 2021-01-15 14:31 UTC
#### What information was incorrect, unhelpful, or incomplete?

Support for `path()` is incorrect

#### What did you expect to see?

Compatibility table should so support in Firefox, Safari, and Edge on desktop.

#### Did you test this? If so, how?

Tested with Firefox(83.0), Safari(13.1.2), Edge(Version 89.0.760.0 (Official build) Dev (64-bit)) using:
https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path

Using the example in:
https://github.com/mdn/interactive-examples/pull/1144

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.clip-path`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path
* Report started: 2021-01-15T14:23:31.636Z

</details>

**Comment by rachelandrew** [comment] 2021-01-18 16:32
Duplicate of https://github.com/mdn/browser-compat-data/issues/8661

**Closed by rachelandrew** 2021-01-18 16:32 UTC
Labels: data:css :art:, duplicate :dancing_women:
